# Exploratory Data Analysis and Insights on Bank Customer Churn Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **Churn_Modelling.csv** dataset contains details of bank customers (credit score, country, age, balance, products and more) and whether each customer left the bank.

**Source:** Kaggle - Churn Modelling (https://www.kaggle.com/datasets/shrutimechlearn/churn-modelling).

The dataset contains:

- **10,000 rows**
- **14 columns**
- **No missing values were found during the initial dataset review**

### Columns in the Dataset

| Column | Description |
|---|---|
| `RowNumber` | Row number (1 to 10,000) |
| `CustomerId` | Unique ID of the customer |
| `Surname` | Surname of the customer |
| `CreditScore` | Credit score of the customer |
| `Geography` | Country of the customer (France, Germany or Spain) |
| `Gender` | Female / Male |
| `Age` | Age of the customer |
| `Tenure` | Number of years the customer has been with the bank |
| `Balance` | Account balance |
| `NumOfProducts` | Number of bank products used by the customer |
| `HasCrCard` | 1 if the customer has a credit card, otherwise 0 |
| `IsActiveMember` | 1 if the customer is an active member, otherwise 0 |
| `EstimatedSalary` | Estimated yearly salary |
| `Exited` | 1 if the customer left the bank, otherwise 0 |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()`, `to_csv()`, `duplicated()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **Churn_Modelling.csv** into a DataFrame named `df`.

In [64]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\Bank_Customer_Churn_Modelling\Bank_Customer_Churn_Modelling.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [65]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Question 3
Display the last **5 rows** of the dataset.

In [66]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### Question 4
Find the total number of **rows and columns** in the dataset.

In [67]:
df.shape

(10000, 14)

### Question 5
Display all the **column names** present in the dataset.

In [68]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [69]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname                str
CreditScore          int64
Geography              str
Gender                 str
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [71]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [72]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

### Question 10
Check whether the **CustomerId** column has any **duplicate values** using `duplicated().sum()`.

In [73]:
df.duplicated().sum()

np.int64(0)

### Question 11
Find how many customers have a **Balance equal to 0**.

In [74]:
df[df['Balance']==0]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.0,1,1,1,101348.88,1
3,4,15701354,Boni,699,France,Female,39,1,0.0,2,0,0,93826.63,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.0,2,1,1,10062.80,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.0,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.0,2,1,0,26260.98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.0,2,1,1,179436.60,0
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.0,1,1,0,195192.40,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.0,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.0,2,1,0,96270.64,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.0,1,0,1,42085.58,1

## 3. Selecting Data

### Question 12
Select and display only the **CreditScore** column.

In [75]:
df['CreditScore']

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

### Question 13
Select and display the **Surname, Geography, and Exited** columns.

In [76]:
df[['Surname','Geography','Exited']]

        Surname Geography  Exited
0      Hargrave    France       1
1          Hill     Spain       0
2          Onio    France       1
3          Boni    France       0
4      Mitchell     Spain       0
...         ...       ...     ...
9995   Obijiaku    France       0
9996  Johnstone    France       0
9997        Liu    France       1
9998  Sabbatini   Germany       1
9999     Walker    France       0

[10000 rows x 3 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [77]:
df.loc[0:10]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0

### Question 15
Using `iloc`, display the first **5 rows and first 4 columns**.

In [78]:
df.iloc[:5,:4]

   RowNumber  CustomerId   Surname  CreditScore
0          1    15634602  Hargrave          619
1          2    15647311      Hill          608
2          3    15619304      Onio          502
3          4    15701354      Boni          699
4          5    15737888  Mitchell          850

### Question 16
Using `loc`, display rows **0 to 4** for the columns **Surname, Age, and Balance**.

In [79]:
df.loc[0:4,['Surname','Age','Balance']]

    Surname  Age    Balance
0  Hargrave   42       0.00
1      Hill   41   83807.86
2      Onio   42  159660.80
3      Boni   39       0.00
4  Mitchell   43  125510.82

## 4. Exploring Unique Values

### Question 17
Display all the **unique values** from the **Geography** column.

In [80]:
df['Geography'].unique()

<StringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str

### Question 18
Find the total number of **unique values** in the **Surname** column.

In [81]:
df['Surname'].nunique()

2932

### Question 19
Display all the **unique values** from the **NumOfProducts** column.

In [82]:
df['NumOfProducts'].unique()

array([1, 3, 2, 4])

### Question 20
Count how many records belong to each **Exited** value using `value_counts()`.

In [83]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

### Question 21
Count how many records belong to each **Geography** value using `value_counts()`.

In [84]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 22
Find the **maximum value** available in the **Balance** column.

In [85]:
df['Balance'].max()

np.float64(250898.09)

### Question 23
Find the **minimum value** available in the **CreditScore** column.

In [86]:
df['CreditScore'].min()

np.int64(350)

### Question 24
Display all rows whose **Age** is greater than **60**.

In [87]:
df[df['Age']>60]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1
85,86,15805254,Ndukaku,652,Spain,Female,75,10,0.00,2,1,1,114675.75,0
104,105,15804919,Dunbabin,670,Spain,Female,65,1,0.00,1,1,1,177655.68,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9832,9833,15814690,Chukwujekwu,595,Germany,Female,64,2,105736.32,1,1,1,89935.73,1
9879,9880,15669414,Pisano,486,Germany,Male,62,9,118356.89,2,1,0,168034.83,1
9894,9895,15704795,Vagin,521,France,Female,77,6,0.00,2,1,1,49054.10,0
9897,9898,15810563,Ho,678,Spain,Female,61,8,0.00,2,1,1,159938.82,0
9936,9937,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0

### Question 25
Display all rows whose **Balance** is greater than **200000**.

In [88]:
df[df['Balance']>200000]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
138,139,15594408,Chia,584,Spain,Female,48,2,213146.20,1,1,0,75161.25,1
520,521,15671256,Macartney,850,France,Female,35,1,211774.31,1,1,0,188574.12,1
720,721,15721658,Fleming,672,Spain,Female,56,2,209767.31,2,1,1,150694.42,1
1067,1068,15599131,Dilke,650,Germany,Male,26,4,214346.96,2,1,0,128815.33,0
1174,1175,15588670,Despeissis,705,Spain,Female,40,5,203715.15,1,1,0,179978.68,1
1365,1366,15689514,Kang,625,France,Male,43,8,201696.07,1,1,0,133020.90,1
1533,1534,15769818,Moore,850,France,Female,37,3,212778.20,1,0,1,69372.88,0
2092,2093,15757408,Lo,655,Spain,Male,38,3,250898.09,3,0,1,81054.00,1
2597,2598,15668818,Chidubem,592,Spain,Female,40,2,200322.45,1,1,1,113244.73,0
2709,2710,15780212,Mao,592,France,Male,37,4,212692.97,1,0,0,176395.02,0
3150,3151,15795298,Olisaemeka,573,Germany,Female,35,9,206868.78,2,0,1,102986.15,0
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
3588,3589,15571958,McIntosh,489,Spain,Male,40,3,221532.80,1,1,0,171867.08,0
3920,3921,15620268,Thomson,634,Germany,Male,43,3,212696.32,1,1,0,115268.86,0
4436,4437,15664498,Golovanov,508,France,Male,26,7,205962.00,1,1,0,156424.40,0
4533,4534,15607275,Ch'ang,850,Spain,Male,39,6,206014.94,2,0,1,42774.84,1
5254,5255,15746664,Ts'ui,463,Spain,Male,20,8,204223.03,1,1,0,128268.39,0
5871,5872,15709920,Burke,479,France,Female,33,2,208165.53,1,0,0,50774.81,1
6271,6272,15620756,Stokes,747,France,Male,49,6,202904.64,1,1,1,17298.72,1
6497,6498,15793688,Bancks,669,France,Male,50,9,201009.64,1,1,0,158032.50,1
6717,6718,15586674,Shaw,663,Spain,Female,58,5,216109.88,1,0,1,74176.71,1
6913,6914,15784180,Ku,564,France,Female,36,7,206329.65,1,1,1,46632.87,1
7353,7354,15736420,Macdonald,596,France,Male,21,4,210433.08,2,0,1,197297.77,1
7492,7493,15776545,Napolitani,682,France,Male,28,10,200724.96,1,0,1,82872.64,1
7632,7633,15620570,Sinnett,736,France,Male,43,4,202443.47,1,1,0,72375.03,0
7887,7888,15745433,Conti,716,Germany,Female,30,2,205770.78,2,0,0,65464.66,0
8027,8028,15769412,Atkinson,684,Spain,Male,39,4,207034.96,2,0,0,157694.76,1
8063,8064,15663888,Connor,549,Germany,Male,34,6,204017.40,2,1,0,109538.35,0
8702,8703,15690589,Udinesi,541,France,Male,37,9,212314.03,1,0,1,148814.54,0
8733,8734,15714241,Haddon,749,Spain,Male,42,9,222267.63,1,0,0,101108.85,1
8794,8795,15578671,Webb,706,Spain,Female,29,1,209490.21,1,1,1,133267.69,1
8982,8983,15627971,Coates,504,France,Female,32,8,206663.75,1,0,0,16281.94,0
9833,9834,15807245,McKay,699,Germany,Female,41,1,200117.76,2,1,0,94142.35,0
9920,9921,15673020,Smith,678,France,Female,49,3,204510.94,1,0,1,738.88,1

### Question 26
Display only the rows where **Geography** is **Germany**.

In [89]:
df[df['Geography']=='Germany']

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

### Question 27
Using `query()`, display all customers who **left the bank** (`Exited` equal to 1).

In [90]:
df.query('Exited ==0')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### Question 28
Display customers from **Germany** who **left the bank** (`Exited` equal to 1).

In [91]:
df.query("Geography == 'Germany' and Exited == 1")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
46,47,15602280,Martin,829,Germany,Female,27,9,112045.67,1,1,1,119708.21,1
47,48,15771573,Okagbue,637,Germany,Female,39,9,137843.80,1,1,1,117622.80,1
53,54,15702298,Parkhill,655,Germany,Male,41,8,125561.97,1,0,0,164040.94,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9960,9961,15681026,Lucciano,795,Germany,Female,33,9,104552.72,1,1,1,120853.83,1
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

## 6. Simple String Operations

### Question 29
Display all customers whose **Surname** starts with the letter `H`.

In [93]:
df[df['Surname'].str.startswith('H')]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,9898,15810563,Ho,678,Spain,Female,61,8,0.00,2,1,1,159938.82,0
9901,9902,15802909,Hu,706,Germany,Female,56,3,139603.22,1,1,1,86383.61,0
9914,9915,15568876,Hughes,496,France,Female,34,1,102723.35,2,1,0,180844.81,0
9951,9952,15763874,Ho,635,Spain,Male,46,8,0.00,2,1,1,60739.16,0
9969,9970,15806360,Hou,609,France,Male,41,6,0.00,1,0,1,112585.19,0

### Question 30
Convert the values in the **Gender** column to uppercase using a Pandas string method and display the result.

In [96]:
df['Gender']=df['Gender'].str.upper()
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,FEMALE,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,FEMALE,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,FEMALE,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,FEMALE,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,FEMALE,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,MALE,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,MALE,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,FEMALE,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,MALE,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,FEMALE,28,4,130142.79,1,1,0,38190.78,0

## 7. Creating and Modifying Columns

### Question 31
Create a new column called **Age Group**. Store `Senior` when `Age` is 60 or more; otherwise store `Adult`. Use `apply()` with a `lambda` function.

In [98]:
df['Age Group'] = df['Age'].apply(lambda x:'Senior' if x>=60 else 'Adult')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age Group
0,1,15634602,Hargrave,619,France,FEMALE,42,2,0.00,1,1,1,101348.88,1,Adult
1,2,15647311,Hill,608,Spain,FEMALE,41,1,83807.86,1,0,1,112542.58,0,Adult
2,3,15619304,Onio,502,France,FEMALE,42,8,159660.80,3,1,0,113931.57,1,Adult
3,4,15701354,Boni,699,France,FEMALE,39,1,0.00,2,0,0,93826.63,0,Adult
4,5,15737888,Mitchell,850,Spain,FEMALE,43,2,125510.82,1,1,1,79084.10,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,MALE,39,5,0.00,2,1,0,96270.64,0,Adult
9996,9997,15569892,Johnstone,516,France,MALE,35,10,57369.61,1,1,1,101699.77,0,Adult
9997,9998,15584532,Liu,709,France,FEMALE,36,7,0.00,1,0,1,42085.58,1,Adult
9998,9999,15682355,Sabbatini,772,Germany,MALE,42,3,75075.31,2,1,0,92888.52,1,Adult
9999,10000,15628319,Walker,792,France,FEMALE,28,4,130142.79,1,1,0,38190.78,0,Adult

### Question 32
Display the first **10 rows** after creating the **Age Group** column.

In [99]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age Group
0,1,15634602,Hargrave,619,France,FEMALE,42,2,0.00,1,1,1,101348.88,1,Adult
1,2,15647311,Hill,608,Spain,FEMALE,41,1,83807.86,1,0,1,112542.58,0,Adult
2,3,15619304,Onio,502,France,FEMALE,42,8,159660.80,3,1,0,113931.57,1,Adult
3,4,15701354,Boni,699,France,FEMALE,39,1,0.00,2,0,0,93826.63,0,Adult
4,5,15737888,Mitchell,850,Spain,FEMALE,43,2,125510.82,1,1,1,79084.10,0,Adult
5,6,15574012,Chu,645,Spain,MALE,44,8,113755.78,2,1,0,149756.71,1,Adult
6,7,15592531,Bartlett,822,France,MALE,50,7,0.00,2,1,1,10062.80,0,Adult
7,8,15656148,Obinna,376,Germany,FEMALE,29,4,115046.74,4,1,0,119346.88,1,Adult
8,9,15792365,He,501,France,MALE,44,4,142051.07,2,0,1,74940.50,0,Adult
9,10,15592389,H?,684,France,MALE,27,2,134603.88,1,1,1,71725.73,0,Adult

### Question 33
Remove the **Age Group** column using `drop()`.

In [ ]:
df.drop('Age Group',axis=1,inplace=True)

### Question 34
Rename the column **Exited** to **Churned**.

In [102]:
df.rename(columns={'Exited':'Churned'},inplace=True)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Churned
0,1,15634602,Hargrave,619,France,FEMALE,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,FEMALE,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,FEMALE,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,FEMALE,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,FEMALE,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,MALE,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,MALE,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,FEMALE,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,MALE,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,FEMALE,28,4,130142.79,1,1,0,38190.78,0

## 8. Conversion and Export

### Question 35
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [103]:
df.select_dtypes(include='number')

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Churned
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

### Question 36
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [104]:
df.head(10).to_numpy()

array([[1, 15634602, 'Hargrave', 619, 'France', 'FEMALE', 42, 2, 0.0, 1,
        1, 1, 101348.88, 1],
       [2, 15647311, 'Hill', 608, 'Spain', 'FEMALE', 41, 1, 83807.86, 1,
        0, 1, 112542.58, 0],
       [3, 15619304, 'Onio', 502, 'France', 'FEMALE', 42, 8, 159660.8, 3,
        1, 0, 113931.57, 1],
       [4, 15701354, 'Boni', 699, 'France', 'FEMALE', 39, 1, 0.0, 2, 0,
        0, 93826.63, 0],
       [5, 15737888, 'Mitchell', 850, 'Spain', 'FEMALE', 43, 2,
        125510.82, 1, 1, 1, 79084.1, 0],
       [6, 15574012, 'Chu', 645, 'Spain', 'MALE', 44, 8, 113755.78, 2, 1,
        0, 149756.71, 1],
       [7, 15592531, 'Bartlett', 822, 'France', 'MALE', 50, 7, 0.0, 2, 1,
        1, 10062.8, 0],
       [8, 15656148, 'Obinna', 376, 'Germany', 'FEMALE', 29, 4,
        115046.74, 4, 1, 0, 119346.88, 1],
       [9, 15792365, 'He', 501, 'France', 'MALE', 44, 4, 142051.07, 2, 0,
        1, 74940.5, 0],
       [10, 15592389, 'H?', 684, 'France', 'MALE', 27, 2, 134603.88, 1,
        1, 1, 71725.73, 0]], dtype=object)

### Question 37
Convert all column names to lowercase using `columns.str.lower()`.

In [106]:
df.columns = df.columns.str.lower()
df

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,churned
0,1,15634602,Hargrave,619,France,FEMALE,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,FEMALE,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,FEMALE,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,FEMALE,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,FEMALE,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,MALE,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,MALE,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,FEMALE,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,MALE,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,FEMALE,28,4,130142.79,1,1,0,38190.78,0

### Question 38
Save only the first **1000 rows** of the DataFrame as a new CSV file named **Churn_Modelling_Practice_Output.csv** using `to_csv()` without saving the index.

In [107]:
df.head(1000).to_csv('Churn_Modelling_Practice_Output.csv',index=True)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.