# Exploratory Data Analysis and Insights on Medical Insurance Costs Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **insurance.csv** dataset contains personal details of insurance customers and the medical charges billed to them.

**Source:** Kaggle - Medical Cost Personal Datasets (https://www.kaggle.com/datasets/mirichoi0218/insurance).

The dataset contains:

- **1,338 rows**
- **7 columns**
- **No missing values were found during the initial dataset review**

### Columns in the Dataset

| Column | Description |
|---|---|
| `age` | Age of the customer |
| `sex` | Gender (male / female) |
| `bmi` | Body mass index |
| `children` | Number of children covered by insurance |
| `smoker` | Whether the customer smokes (yes / no) |
| `region` | Residential area in the US (northeast, northwest, southeast, southwest) |
| `charges` | Medical costs billed by the insurance company |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()` and `to_csv()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **insurance.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\Medical_Cost_Insurance\Medical Cost_Personal_Datasets.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### Question 3
Display the last **5 rows** of the dataset.

In [3]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

### Question 4
Find the total number of **rows and columns** in the dataset.

In [4]:
df.shape

(1338, 7)

### Question 5
Display all the **column names** present in the dataset.

In [5]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='str')

### Question 6
Display the **data type of each column**.

In [6]:
df.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [9]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

## 3. Selecting Data

### Question 10
Select and display only the **region** column.

In [10]:
df['region']

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: str

### Question 11
Select and display the **age, bmi, and charges** columns.

In [11]:
df[['age','bmi','charges']]

      age     bmi      charges
0      19  27.900  16884.92400
1      18  33.770   1725.55230
2      28  33.000   4449.46200
3      33  22.705  21984.47061
4      32  28.880   3866.85520
...   ...     ...          ...
1333   50  30.970  10600.54830
1334   18  31.920   2205.98080
1335   18  36.850   1629.83350
1336   21  25.800   2007.94500
1337   61  29.070  29141.36030

[1338 rows x 3 columns]

### Question 12
Display the first **10 rows** using DataFrame slicing.

In [12]:
df.loc[0:10]

    age     sex     bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
1    18    male  33.770         1     no  southeast   1725.55230
2    28    male  33.000         3     no  southeast   4449.46200
3    33    male  22.705         0     no  northwest  21984.47061
4    32    male  28.880         0     no  northwest   3866.85520
5    31  female  25.740         0     no  southeast   3756.62160
6    46  female  33.440         1     no  southeast   8240.58960
7    37  female  27.740         3     no  northwest   7281.50560
8    37    male  29.830         2     no  northeast   6406.41070
9    60  female  25.840         0     no  northwest  28923.13692
10   25    male  26.220         0     no  northeast   2721.32080

### Question 13
Using `iloc`, display the first **5 rows and first 4 columns**.

In [13]:
df.iloc[:5,:4]

   age     sex     bmi  children
0   19  female  27.900         0
1   18    male  33.770         1
2   28    male  33.000         3
3   33    male  22.705         0
4   32    male  28.880         0

### Question 14
Using `loc`, display rows **0 to 4** for the columns **age, sex, and smoker**.

In [14]:
df.loc[0:4,['age','sex','smoker']]

   age     sex smoker
0   19  female    yes
1   18    male     no
2   28    male     no
3   33    male     no
4   32    male     no

## 4. Exploring Unique Values

### Question 15
Display all the **unique values** from the **region** column.

In [15]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

### Question 16
Find the total number of **unique values** in the **region** column.

In [16]:
df['region'].nunique()

4

### Question 17
Display all the **unique values** from the **smoker** column.

In [17]:
df['smoker'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

### Question 18
Count how many records belong to each **smoker** value using `value_counts()`.

In [18]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

### Question 19
Count how many records belong to each **children** value using `value_counts()`.

In [19]:
df['children'].value_counts()

children
0    574
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 20
Find the **maximum value** available in the **charges** column.

In [20]:
df['charges'].max()

np.float64(63770.42801)

### Question 21
Display all rows whose **charges** is greater than **30000**.

In [21]:
df[df['charges']>30000]

      age     sex     bmi  children smoker     region      charges
14     27    male  42.130         0    yes  southeast  39611.75770
19     30    male  35.300         0    yes  southwest  36837.46700
23     34  female  31.920         1    yes  northeast  37701.87680
29     31    male  36.300         2    yes  southwest  38711.00000
30     22    male  35.600         0    yes  southwest  35585.57600
...   ...     ...     ...       ...    ...        ...          ...
1301   62    male  30.875         3    yes  northwest  46718.16325
1303   43    male  27.800         0    yes  southwest  37829.72420
1308   25  female  30.200         0    yes  southwest  33900.65300
1313   19  female  34.700         2    yes  southwest  36397.57600
1323   42  female  40.370         2    yes  southeast  43896.37630

[162 rows x 7 columns]

### Question 22
Display all rows whose **bmi** is greater than **35**.

In [22]:
df[df['bmi']>35]

      age     sex     bmi  children smoker     region      charges
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
18     56    male  40.300         0     no  southwest  10602.38500
19     30    male  35.300         0    yes  southwest  36837.46700
20     60  female  36.005         0     no  northeast  13228.84695
...   ...     ...     ...       ...    ...        ...          ...
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1329   52    male  38.600         2     no  southwest  10325.20600
1332   52  female  44.700         3     no  southwest  11411.68500
1335   18  female  36.850         0     no  southeast   1629.83350

[316 rows x 7 columns]

### Question 23
Display only the rows where **smoker** is **yes**.

In [23]:
df[df['smoker']=='yes']

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
11     62  female  26.290         0    yes  southeast  27808.72510
14     27    male  42.130         0    yes  southeast  39611.75770
19     30    male  35.300         0    yes  southwest  36837.46700
23     34  female  31.920         1    yes  northeast  37701.87680
...   ...     ...     ...       ...    ...        ...          ...
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1321   62    male  26.695         0    yes  northeast  28101.33305
1323   42  female  40.370         2    yes  southeast  43896.37630
1337   61  female  29.070         0    yes  northwest  29141.36030

[274 rows x 7 columns]

### Question 24
Using `query()`, display all customers having **3 children**.

In [24]:
df.query('children == 3')

      age     sex     bmi  children smoker     region      charges
2      28    male  33.000         3     no  southeast   4449.46200
7      37  female  27.740         3     no  northwest   7281.50560
25     59  female  27.720         3     no  southeast  14001.13380
36     62  female  32.965         3     no  northwest  15612.19335
54     40  female  28.690         3     no  northwest   8059.67910
...   ...     ...     ...       ...    ...        ...          ...
1301   62    male  30.875         3    yes  northwest  46718.16325
1314   30  female  23.655         3    yes  northwest  18765.87545
1320   31    male  31.065         3     no  northwest   5425.02335
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830

[157 rows x 7 columns]

### Question 25
Display customers who are **smokers** and whose **age is greater than 50**.

In [25]:
df.query('smoker == "yes" and age>50')

      age     sex     bmi  children smoker     region      charges
11     62  female  26.290         0    yes  southeast  27808.72510
39     60    male  39.900         0    yes  southwest  48173.36100
55     58    male  36.955         2    yes  northwest  47496.49445
58     53  female  22.880         1    yes  southeast  23244.79020
86     57  female  31.160         0    yes  northwest  43578.93940
...   ...     ...     ...       ...    ...        ...          ...
1265   64    male  23.760         0    yes  southeast  26926.51440
1284   61    male  36.300         1    yes  southwest  47403.88000
1301   62    male  30.875         3    yes  northwest  46718.16325
1321   62    male  26.695         0    yes  northeast  28101.33305
1337   61  female  29.070         0    yes  northwest  29141.36030

[64 rows x 7 columns]

## 6. Simple String Operations

### Question 26
Display all rows where the **region** starts with the word `south`.

In [27]:
df[df['region'].str.startswith('south')]

      age     sex    bmi  children smoker     region      charges
0      19  female  27.90         0    yes  southwest  16884.92400
1      18    male  33.77         1     no  southeast   1725.55230
2      28    male  33.00         3     no  southeast   4449.46200
5      31  female  25.74         0     no  southeast   3756.62160
6      46  female  33.44         1     no  southeast   8240.58960
...   ...     ...    ...       ...    ...        ...          ...
1330   57  female  25.74         2     no  southeast  12629.16560
1331   23  female  33.40         0     no  southwest  10795.93733
1332   52  female  44.70         3     no  southwest  11411.68500
1335   18  female  36.85         0     no  southeast   1629.83350
1336   21  female  25.80         0     no  southwest   2007.94500

[689 rows x 7 columns]

### Question 27
Convert the values in the **region** column to uppercase using a Pandas string method and display the result.

In [33]:
df['region'] = df['region'].str.upper()
df

      age     sex     bmi  children smoker  region      charges
0      19  female  27.900         0    yes     NaN  16884.92400
1      18    male  33.770         1     no     NaN   1725.55230
2      28    male  33.000         3     no     NaN   4449.46200
3      33    male  22.705         0     no     NaN  21984.47061
4      32    male  28.880         0     no     NaN   3866.85520
...   ...     ...     ...       ...    ...     ...          ...
1333   50    male  30.970         3     no     NaN  10600.54830
1334   18  female  31.920         0     no     NaN   2205.98080
1335   18  female  36.850         0     no     NaN   1629.83350
1336   21  female  25.800         0     no     NaN   2007.94500
1337   61  female  29.070         0    yes     NaN  29141.36030

[1338 rows x 7 columns]

## 7. Creating and Modifying Columns

### Question 28
Create a new column called **Charge Level**. Store `High` when `charges` is greater than 20000; otherwise store `Normal`. Use `apply()` with a `lambda` function.

In [35]:
df['Charge Level'] = df['charges'].apply(lambda x:'High' if x>20000 else 'Low')
df

      age     sex     bmi  children smoker  region      charges Charge Level
0      19  female  27.900         0    yes     NaN  16884.92400          Low
1      18    male  33.770         1     no     NaN   1725.55230          Low
2      28    male  33.000         3     no     NaN   4449.46200          Low
3      33    male  22.705         0     no     NaN  21984.47061         High
4      32    male  28.880         0     no     NaN   3866.85520          Low
...   ...     ...     ...       ...    ...     ...          ...          ...
1333   50    male  30.970         3     no     NaN  10600.54830          Low
1334   18  female  31.920         0     no     NaN   2205.98080          Low
1335   18  female  36.850         0     no     NaN   1629.83350          Low
1336   21  female  25.800         0     no     NaN   2007.94500          Low
1337   61  female  29.070         0    yes     NaN  29141.36030         High

[1338 rows x 8 columns]

### Question 29
Display the first **10 rows** after creating the **Charge Level** column.

In [36]:
df.head(10)

   age     sex     bmi  children smoker  region      charges Charge Level
0   19  female  27.900         0    yes     NaN  16884.92400          Low
1   18    male  33.770         1     no     NaN   1725.55230          Low
2   28    male  33.000         3     no     NaN   4449.46200          Low
3   33    male  22.705         0     no     NaN  21984.47061         High
4   32    male  28.880         0     no     NaN   3866.85520          Low
5   31  female  25.740         0     no     NaN   3756.62160          Low
6   46  female  33.440         1     no     NaN   8240.58960          Low
7   37  female  27.740         3     no     NaN   7281.50560          Low
8   37    male  29.830         2     no     NaN   6406.41070          Low
9   60  female  25.840         0     no     NaN  28923.13692         High

### Question 30
Remove the **Charge Level** column using `drop()`.

In [40]:
df.drop('Charge Level',axis=1,inplace=True)

### Question 31
Rename the column **charges** to **Medical_Charges**.

In [41]:
df.rename(columns={'charges':'Medical_Charges'})

      age     sex     bmi  children smoker  region  Medical_Charges
0      19  female  27.900         0    yes     NaN      16884.92400
1      18    male  33.770         1     no     NaN       1725.55230
2      28    male  33.000         3     no     NaN       4449.46200
3      33    male  22.705         0     no     NaN      21984.47061
4      32    male  28.880         0     no     NaN       3866.85520
...   ...     ...     ...       ...    ...     ...              ...
1333   50    male  30.970         3     no     NaN      10600.54830
1334   18  female  31.920         0     no     NaN       2205.98080
1335   18  female  36.850         0     no     NaN       1629.83350
1336   21  female  25.800         0     no     NaN       2007.94500
1337   61  female  29.070         0    yes     NaN      29141.36030

[1338 rows x 7 columns]

## 8. Conversion and Export

### Question 32
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [43]:
df.select_dtypes(include='number')

      age     bmi  children  region      charges
0      19  27.900         0     NaN  16884.92400
1      18  33.770         1     NaN   1725.55230
2      28  33.000         3     NaN   4449.46200
3      33  22.705         0     NaN  21984.47061
4      32  28.880         0     NaN   3866.85520
...   ...     ...       ...     ...          ...
1333   50  30.970         3     NaN  10600.54830
1334   18  31.920         0     NaN   2205.98080
1335   18  36.850         0     NaN   1629.83350
1336   21  25.800         0     NaN   2007.94500
1337   61  29.070         0     NaN  29141.36030

[1338 rows x 5 columns]

### Question 33
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [44]:
df.head(10).to_numpy()

array([[19, 'female', 27.9, 0, 'yes', nan, 16884.924],
       [18, 'male', 33.77, 1, 'no', nan, 1725.5523],
       [28, 'male', 33.0, 3, 'no', nan, 4449.462],
       [33, 'male', 22.705, 0, 'no', nan, 21984.47061],
       [32, 'male', 28.88, 0, 'no', nan, 3866.8552],
       [31, 'female', 25.74, 0, 'no', nan, 3756.6216],
       [46, 'female', 33.44, 1, 'no', nan, 8240.5896],
       [37, 'female', 27.74, 3, 'no', nan, 7281.5056],
       [37, 'male', 29.83, 2, 'no', nan, 6406.4107],
       [60, 'female', 25.84, 0, 'no', nan, 28923.13692]], dtype=object)

### Question 34
Convert all column names to uppercase using `columns.str.upper()`.

In [46]:
df.columns = df.columns.str.upper()
df

      AGE     SEX     BMI  CHILDREN SMOKER  REGION      CHARGES
0      19  female  27.900         0    yes     NaN  16884.92400
1      18    male  33.770         1     no     NaN   1725.55230
2      28    male  33.000         3     no     NaN   4449.46200
3      33    male  22.705         0     no     NaN  21984.47061
4      32    male  28.880         0     no     NaN   3866.85520
...   ...     ...     ...       ...    ...     ...          ...
1333   50    male  30.970         3     no     NaN  10600.54830
1334   18  female  31.920         0     no     NaN   2205.98080
1335   18  female  36.850         0     no     NaN   1629.83350
1336   21  female  25.800         0     no     NaN   2007.94500
1337   61  female  29.070         0    yes     NaN  29141.36030

[1338 rows x 7 columns]

### Question 35
Save the DataFrame as a new CSV file named **Insurance_Practice_Output.csv** using `to_csv()` without saving the index.

In [47]:
df.to_csv('Insurance_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.