# Exploratory Data Analysis and Insights on Twitter US Airline Sentiment Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **Tweets.csv** dataset contains tweets (February 2015) about major US airlines, each labelled as `positive`, `neutral` or `negative`, along with the reason for negative tweets.

**Source:** Kaggle - Twitter US Airline Sentiment (https://www.kaggle.com/datasets/crowdflower/twitter-airline-sentiment).

The dataset contains:

- **14,640 rows**
- **15 columns**
- **Missing values are present** in several columns (such as `negativereason`, `negativereason_confidence`, `airline_sentiment_gold`, `negativereason_gold`, `tweet_coord`, `tweet_location` and `user_timezone`)

### Columns in the Dataset

| Column | Description |
|---|---|
| `tweet_id` | Unique ID of the tweet |
| `airline_sentiment` | Sentiment of the tweet: `negative`, `neutral` or `positive` |
| `airline_sentiment_confidence` | How sure the reviewers were about the sentiment (0 to 1) |
| `negativereason` | Reason for a negative tweet (for example `Late Flight` or `Customer Service Issue`) |
| `negativereason_confidence` | How sure the reviewers were about the negative reason |
| `airline` | Airline the tweet is about (American, Delta, Southwest, United, US Airways, Virgin America) |
| `airline_sentiment_gold`, `negativereason_gold` | Extra reviewer labels, almost always empty |
| `name` | Twitter user name |
| `retweet_count` | Number of times the tweet was retweeted |
| `text` | Text of the tweet |
| `tweet_coord` | Location coordinates of the tweet |
| `tweet_created` | Date and time the tweet was posted |
| `tweet_location` | Location written by the user |
| `user_timezone` | Time zone of the user |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()`, `to_csv()`, `str.contains()`, `str.len()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **Tweets.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\Twitter\Tweets.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [ ]:
df.head()

### Question 3
Display the last **5 rows** of the dataset.

In [2]:
df.tail()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada)
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN

### Question 4
Find the total number of **rows and columns** in the dataset.

In [3]:
df.shape

(14640, 15)

### Question 5
Display all the **column names** present in the dataset.

In [4]:
df.columns

Index(['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence',
       'negativereason', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [5]:
df.dtypes

tweet_id                          int64
airline_sentiment                   str
airline_sentiment_confidence    float64
negativereason                      str
negativereason_confidence       float64
airline                             str
airline_sentiment_gold              str
name                                str
negativereason_gold                 str
retweet_count                     int64
text                                str
tweet_coord                         str
tweet_created                       str
tweet_location                      str
user_timezone                       str
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   tweet_id                      14640 non-null  int64
 1   airline_sentiment             14640 non-null  str
 2   airline_sentiment_confidence  14640 non-null  float64
 3   negativereason                9178 non-null   str
 4   negativereason_confidence     10522 non-null  float64
 5   airline                       14640 non-null  str
 6   airline_sentiment_gold        40 non-null     str
 7   name                          14640 non-null  str
 8   negativereason_gold           32 non-null     str
 9   retweet_count                 14640 non-null  int64
 10  text                          14640 non-null  str
 11  tweet_coord                   1019 non-null   str
 12  tweet_created                 14640 non-null  str
 13  tweet_location                9907 non-null   str
 14  user_timezone                 9820 non-null   str
dtypes: float64(2), int64(2), str(11)
memory usage: 1.7 MB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [8]:
df.isnull().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [9]:
df.isna().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

### Question 10
Display only the columns that have **at least one missing value** (hint: store `df.isnull().sum()` in a variable and filter it).

In [10]:
a = df.isnull().sum()
a[a > 0]

negativereason                5462
negativereason_confidence     4118
airline_sentiment_gold       14600
negativereason_gold          14608
tweet_coord                  13621
tweet_location                4733
user_timezone                 4820
dtype: int64

### Question 11
Find the **percentage of missing values** in the **negativereason** column.

In [11]:
df['negativereason'].isnull().mean() * 100

np.float64(37.30874316939891)

## 3. Selecting Data

### Question 12
Select and display only the **text** column.

In [12]:
df['text']

0                      @VirginAmerica What @dhepburn said.
1        @VirginAmerica plus you've added commercials t...
2        @VirginAmerica I didn't today... Must mean I n...
3        @VirginAmerica it's really aggressive to blast...
4        @VirginAmerica and it's a really big bad thing...
                               ...
14635    @AmericanAir thank you we got on a different f...
14636    @AmericanAir leaving over 20 minutes Late Flig...
14637    @AmericanAir Please bring American Airlines to...
14638    @AmericanAir you have my money, you change my ...
14639    @AmericanAir we have 8 ppl so we need 2 know h...
Name: text, Length: 14640, dtype: str

### Question 13
Select and display the **airline, airline_sentiment, and text** columns.

In [13]:
df[['airline','airline_sentiment','text']]

,airline,airline_sentiment,text
0,Virgin America,neutral,@VirginAmerica What @dhepburn said.
1,Virgin America,positive,@VirginAmerica plus you've added commercials t...
2,Virgin America,neutral,@VirginAmerica I didn't today... Must mean I n...
3,Virgin America,negative,@VirginAmerica it's really aggressive to blast...
4,Virgin America,negative,@VirginAmerica and it's a really big bad thing...
...,...,...,...
14635,American,positive,@AmericanAir thank you we got on a different f...
14636,American,negative,@AmericanAir leaving over 20 minutes Late Flig...
14637,American,neutral,@AmericanAir Please bring American Airlines to...
14638,American,negative,"@AmericanAir you have my money, you change my ..."
14639,American,neutral,@AmericanAir we have 8 ppl so we need 2 know h...

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [14]:
df.loc[0:10]

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)
5,570300767074181121,negative,1.0000,Can't Tell,0.6842,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica seriously would pay $30 a fligh...,NaN,2015-02-24 11:14:33 -0800,NaN,Pacific Time (US & Canada)
6,570300616901320704,positive,0.6745,NaN,0.0000,Virgin America,NaN,cjmcginnis,NaN,0,"@VirginAmerica yes, nearly every time I fly VX...",NaN,2015-02-24 11:13:57 -0800,San Francisco CA,Pacific Time (US & Canada)
7,570300248553349120,neutral,0.6340,NaN,NaN,Virgin America,NaN,pilot,NaN,0,@VirginAmerica Really missed a prime opportuni...,NaN,2015-02-24 11:12:29 -0800,Los Angeles,Pacific Time (US & Canada)
8,570299953286942721,positive,0.6559,NaN,NaN,Virgin America,NaN,dhepburn,NaN,0,"@virginamerica Well, I didn't…but NOW I DO! :-D",NaN,2015-02-24 11:11:19 -0800,San Diego,Pacific Time (US & Canada)
9,570295459631263746,positive,1.0000,NaN,NaN,Virgin America,NaN,YupitsTate,NaN,0,"@VirginAmerica it was amazing, and arrived an ...",NaN,2015-02-24 10:53:27 -0800,Los Angeles,Eastern Time (US & Canada)
10,570294189143031808,neutral,0.6769,NaN,0.0000,Virgin America,NaN,idk_but_youtube,NaN,0,@VirginAmerica did you know that suicide is th...,NaN,2015-02-24 10:48:24 -0800,1/1 loner squad,Eastern Time (US & Canada)

### Question 15
Using `iloc`, display the first **5 rows and first 4 columns**.

In [15]:
df.iloc[:5,:4]

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason
0,570306133677760513,neutral,1.0000,NaN
1,570301130888122368,positive,0.3486,NaN
2,570301083672813571,neutral,0.6837,NaN
3,570301031407624196,negative,1.0000,Bad Flight
4,570300817074462722,negative,1.0000,Can't Tell

### Question 16
Using `loc`, display rows **0 to 4** for the columns **tweet_id, airline, and airline_sentiment**.

In [18]:
df.loc[0:4,['tweet_id','airline','airline_sentiment']]

             tweet_id         airline airline_sentiment
0  570306133677760513  Virgin America           neutral
1  570301130888122368  Virgin America          positive
2  570301083672813571  Virgin America           neutral
3  570301031407624196  Virgin America          negative
4  570300817074462722  Virgin America          negative

## 4. Exploring Unique Values

### Question 17
Display all the **unique values** from the **airline** column.

In [19]:
df['airline'].unique()

<StringArray>
['Virgin America', 'United', 'Southwest', 'Delta', 'US Airways', 'American']
Length: 6, dtype: str

### Question 18
Find the total number of **unique values** in the **airline** column.

In [20]:
df['airline'].nunique()

6

### Question 19
Display all the **unique values** from the **airline_sentiment** column.

In [21]:
df['airline_sentiment'].unique()

<StringArray>
['neutral', 'positive', 'negative']
Length: 3, dtype: str

### Question 20
Count how many records belong to each **airline_sentiment** value using `value_counts()`.

In [22]:
df['airline_sentiment'].value_counts()

airline_sentiment
negative    9178
neutral     3099
positive    2363
Name: count, dtype: int64

### Question 21
Count how many records belong to each **airline** value using `value_counts()`.

In [23]:
df['airline'].value_counts()

airline
United            3822
US Airways        2913
American          2759
Southwest         2420
Delta             2222
Virgin America     504
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 22
Find the **maximum value** available in the **retweet_count** column.

In [24]:
df['retweet_count'].max()

np.int64(44)

### Question 23
Display all rows whose **airline_sentiment_confidence** is greater than **0.9**.

In [25]:
df[df['airline_sentiment_confidence']>0.9]

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
3,570301031407624196,negative,1.0,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)
5,570300767074181121,negative,1.0,Can't Tell,0.6842,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica seriously would pay $30 a fligh...,NaN,2015-02-24 11:14:33 -0800,NaN,Pacific Time (US & Canada)
9,570295459631263746,positive,1.0,NaN,NaN,Virgin America,NaN,YupitsTate,NaN,0,"@VirginAmerica it was amazing, and arrived an ...",NaN,2015-02-24 10:53:27 -0800,Los Angeles,Eastern Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14631,569588464896876545,negative,1.0,Bad Flight,1.0000,American,NaN,MDDavis7,NaN,0,@AmericanAir thx for nothing on getting us out...,NaN,2015-02-22 12:04:07 -0800,US,Eastern Time (US & Canada)
14633,569587705937600512,negative,1.0,Cancelled Flight,1.0000,American,NaN,RussellsWriting,NaN,0,@AmericanAir my flight was Cancelled Flightled...,NaN,2015-02-22 12:01:06 -0800,Los Angeles,Arizona
14636,569587371693355008,negative,1.0,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN
14637,569587242672398336,neutral,1.0,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN
14638,569587188687634433,negative,1.0,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada)

### Question 24
Display only the rows where **airline_sentiment** is **negative**.

In [26]:
df[df['airline_sentiment']=='negative']

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)
5,570300767074181121,negative,1.0000,Can't Tell,0.6842,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica seriously would pay $30 a fligh...,NaN,2015-02-24 11:14:33 -0800,NaN,Pacific Time (US & Canada)
15,570282469121007616,negative,0.6842,Late Flight,0.3684,Virgin America,NaN,smartwatermelon,NaN,0,@VirginAmerica SFO-PDX schedule is still MIA.,NaN,2015-02-24 10:01:50 -0800,"palo alto, ca",Pacific Time (US & Canada)
17,570276917301137409,negative,1.0000,Bad Flight,1.0000,Virgin America,NaN,heatherovieda,NaN,0,@VirginAmerica I flew from NYC to SFO last we...,NaN,2015-02-24 09:39:46 -0800,this place called NYC,Eastern Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14631,569588464896876545,negative,1.0000,Bad Flight,1.0000,American,NaN,MDDavis7,NaN,0,@AmericanAir thx for nothing on getting us out...,NaN,2015-02-22 12:04:07 -0800,US,Eastern Time (US & Canada)
14633,569587705937600512,negative,1.0000,Cancelled Flight,1.0000,American,NaN,RussellsWriting,NaN,0,@AmericanAir my flight was Cancelled Flightled...,NaN,2015-02-22 12:01:06 -0800,Los Angeles,Arizona
14634,569587691626622976,negative,0.6684,Late Flight,0.6684,American,NaN,GolfWithWoody,NaN,0,@AmericanAir right on cue with the delays👌,NaN,2015-02-22 12:01:02 -0800,NaN,Quito
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada)

### Question 25
Display only the rows where **airline** is **Delta**.

In [27]:
df[df['airline']=='Delta']

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
6746,570309345281486848,positive,0.6469,NaN,NaN,Delta,NaN,jaxbra,NaN,0,@JetBlue Yesterday on my way from EWR to FLL j...,NaN,2015-02-24 11:48:38 -0800,"east brunswick, nj",Atlantic Time (Canada)
6747,570309308937842688,neutral,0.6869,NaN,NaN,Delta,NaN,Oneladyyouadore,NaN,0,@JetBlue I hope so because I fly very often an...,NaN,2015-02-24 11:48:29 -0800,Georgia,Quito
6748,570308513181904901,neutral,1.0000,NaN,NaN,Delta,NaN,Oneladyyouadore,NaN,0,"@JetBlue flight 1041 to Savannah, GA",NaN,2015-02-24 11:45:20 -0800,Georgia,Quito
6749,570307820962373632,negative,1.0000,Flight Attendant Complaints,0.6522,Delta,NaN,Oneladyyouadore,NaN,0,"@JetBlue They weren't on any flight, they just...",NaN,2015-02-24 11:42:34 -0800,Georgia,Quito
6750,570305363859406848,negative,1.0000,Bad Flight,1.0000,Delta,NaN,Oneladyyouadore,NaN,0,@JetBlue everyone is here but our pilots are n...,NaN,2015-02-24 11:32:49 -0800,Georgia,Quito
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8963,567667301067915264,neutral,1.0000,NaN,NaN,Delta,NaN,BritishAirNews,NaN,0,"@JetBlue CEO weighs profits, flyers - @Chronic...",NaN,2015-02-17 04:50:05 -0800,UK,Sydney
8964,567590027375702016,negative,1.0000,Can't Tell,0.6503,Delta,NaN,nesi_1992,NaN,0,@JetBlue is REALLY getting on my nerves !! 😡😡 ...,NaN,2015-02-16 23:43:02 -0800,undecided,Pacific Time (US & Canada)
8965,567588278875213824,neutral,1.0000,NaN,NaN,Delta,NaN,JetBlueNews,NaN,0,@JetBlue's new CEO seeks the right balance to ...,NaN,2015-02-16 23:36:05 -0800,USA,Sydney
12038,570294451261874177,negative,1.0000,longlines,0.4686,Delta,negative,DetroitRonin,Customer Service Issue,0,@DeltaAssist now at 57 minutes waiting on Silv...,NaN,2015-02-24 10:49:27 -0800,Thataway,Eastern Time (US & Canada)
12039,568757671819661314,negative,0.7991,Can't Tell,0.6423,Delta,negative,ConnieBowman4,Customer Service Issue\nCan't Tell,0,@DeltaAssist what I have to say is more than 1...,NaN,2015-02-20 05:02:50 -0800,NaN,NaN

### Question 26
Using `query()`, display all tweets where **airline_sentiment** is `positive`.

In [29]:
df.query('airline_sentiment == "positive"')

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
1,570301130888122368,positive,0.3486,NaN,0.0,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
6,570300616901320704,positive,0.6745,NaN,0.0,Virgin America,NaN,cjmcginnis,NaN,0,"@VirginAmerica yes, nearly every time I fly VX...",NaN,2015-02-24 11:13:57 -0800,San Francisco CA,Pacific Time (US & Canada)
8,570299953286942721,positive,0.6559,NaN,NaN,Virgin America,NaN,dhepburn,NaN,0,"@virginamerica Well, I didn't…but NOW I DO! :-D",NaN,2015-02-24 11:11:19 -0800,San Diego,Pacific Time (US & Canada)
9,570295459631263746,positive,1.0000,NaN,NaN,Virgin America,NaN,YupitsTate,NaN,0,"@VirginAmerica it was amazing, and arrived an ...",NaN,2015-02-24 10:53:27 -0800,Los Angeles,Eastern Time (US & Canada)
11,570289724453216256,positive,1.0000,NaN,NaN,Virgin America,NaN,HyperCamiLax,NaN,0,@VirginAmerica I &lt;3 pretty graphics. so muc...,NaN,2015-02-24 10:30:40 -0800,NYC,America/New_York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14623,569590013278756865,positive,0.6274,NaN,0.0,American,NaN,Flora_Lola_NYC,NaN,0,@AmericanAir Love the new planes for the JFK-L...,NaN,2015-02-22 12:10:16 -0800,NaN,Eastern Time (US & Canada)
14625,569589643487928321,positive,1.0000,NaN,NaN,American,NaN,DrCaseyJRudkin,NaN,0,@AmericanAir Flight 236 was great. Fantastic c...,"[40.64946781, -73.76624703]",2015-02-22 12:08:48 -0800,East Coast,NaN
14628,569588651925098496,positive,1.0000,NaN,NaN,American,NaN,jlhalldc,NaN,0,Thank you. “@AmericanAir: @jlhalldc Customer R...,NaN,2015-02-22 12:04:51 -0800,"Washington, DC",Eastern Time (US & Canada)
14630,569588473050611712,positive,1.0000,NaN,NaN,American,NaN,Laurelinesblog,NaN,0,@AmericanAir Thanks! He is.,NaN,2015-02-22 12:04:09 -0800,"Chapel Hill, NC",NaN
14635,569587686496825344,positive,0.3487,NaN,0.0,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN

### Question 27
Display tweets about **United** that have **airline_sentiment equal to negative**.

In [30]:
df[(df['airline'] == 'United') & (df['airline_sentiment'] == 'negative')]

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
506,570307109704900608,negative,1.0000,Cancelled Flight,0.7030,United,NaN,CoralReefer420,NaN,0,@united still no refund or word via DM. Please...,NaN,2015-02-24 11:39:45 -0800,"Bay Area, California",Alaska
507,570307026263384064,negative,1.0000,Late Flight,1.0000,United,NaN,lsalazarll,NaN,0,@united Delayed due to lack of crew and now de...,NaN,2015-02-24 11:39:25 -0800,NaN,Mountain Time (US & Canada)
509,570306217001799680,negative,0.3475,Can't Tell,0.3475,United,NaN,samidip,NaN,0,@united Your ERI-ORD express connections are h...,NaN,2015-02-24 11:36:12 -0800,"Erie, PA",Eastern Time (US & Canada)
511,570304912468402177,negative,0.6667,Can't Tell,0.3333,United,NaN,andycheco,NaN,0,@united you think you boarded flight AU1066 to...,"[19.43706642, -99.07927123]",2015-02-24 11:31:01 -0800,New York,Eastern Time (US & Canada)
513,570302023993831425,negative,0.6735,Bad Flight,0.3476,United,NaN,slandail,NaN,0,@united Gate agent hooked me up with alternate...,NaN,2015-02-24 11:19:32 -0800,"Columbus, Ohio",Eastern Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4321,567614049425555457,negative,1.0000,Customer Service Issue,0.3545,United,NaN,JustOGG,NaN,0,"@united, link to current status of flights/air...",NaN,2015-02-17 01:18:29 -0800,Tweets = My Opinion,Eastern Time (US & Canada)
4322,567595670463205376,negative,1.0000,Late Flight,1.0000,United,NaN,CRomerDome,NaN,0,@united I like delays less than you because I'...,NaN,2015-02-17 00:05:27 -0800,"Portland, OR",Pacific Time (US & Canada)
4323,567594579310825473,negative,1.0000,Bad Flight,0.6707,United,NaN,brenduch,NaN,0,@united and don't hope for me having a nicer f...,NaN,2015-02-17 00:01:07 -0800,NaN,Buenos Aires
4324,567592368451248130,negative,1.0000,Late Flight,1.0000,United,NaN,brenduch,NaN,0,@united the we got into the gate at IAH on tim...,NaN,2015-02-16 23:52:20 -0800,NaN,Buenos Aires
4325,567591480085463040,negative,1.0000,Late Flight,0.3460,United,NaN,CPoutloud,NaN,0,@united yes. We waited in line for almost an h...,NaN,2015-02-16 23:48:48 -0800,"Washington, DC",NaN

### Question 28
Display only the rows where **negativereason** is **Late Flight**.

In [31]:
df.query('negativereason =="Late Flight"')

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
15,570282469121007616,negative,0.6842,Late Flight,0.3684,Virgin America,NaN,smartwatermelon,NaN,0,@VirginAmerica SFO-PDX schedule is still MIA.,NaN,2015-02-24 10:01:50 -0800,"palo alto, ca",Pacific Time (US & Canada)
67,569973821396152323,negative,1.0000,Late Flight,0.6789,Virgin America,NaN,noelduan,NaN,0,"@VirginAmerica Hi, Virgin! I'm on hold for 40-...",NaN,2015-02-23 13:35:23 -0800,SF ↔ NY,Eastern Time (US & Canada)
82,569933405506310144,negative,0.6792,Late Flight,0.3477,Virgin America,NaN,arieldaie,NaN,0,@VirginAmerica you're the best!! Whenever I (b...,NaN,2015-02-23 10:54:47 -0800,Los Angeles,NaN
93,569911674158731264,negative,1.0000,Late Flight,1.0000,Virgin America,NaN,GunsNDip,NaN,0,"@VirginAmerica just landed in LAX, an hour aft...",NaN,2015-02-23 09:28:26 -0800,NaN,Pacific Time (US & Canada)
101,569892199690678272,negative,1.0000,Late Flight,0.6882,Virgin America,NaN,GunsNDip,NaN,0,@VirginAmerica why must a traveler miss a flig...,NaN,2015-02-23 08:11:03 -0800,NaN,Pacific Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14597,569593278636675072,negative,1.0000,Late Flight,1.0000,American,NaN,otisday,NaN,0,@AmericanAir @Stone9956 Do you dislike delays ...,NaN,2015-02-22 12:23:14 -0800,Pekin,Eastern Time (US & Canada)
14601,569592830307508224,negative,1.0000,Late Flight,0.7123,American,NaN,Jess_JCW,NaN,0,@AmericanAir .....and they waited 5 hours in a...,NaN,2015-02-22 12:21:27 -0800,London,London
14622,569590191758962688,negative,1.0000,Late Flight,0.3358,American,NaN,Jill_Lynnette,NaN,0,I just need a place to sleep when I land witho...,NaN,2015-02-22 12:10:58 -0800,NaN,Eastern Time (US & Canada)
14626,569589460226183168,negative,1.0000,Late Flight,1.0000,American,NaN,cataattack,NaN,0,@AmericanAir Flight 953 NYC-Buenos Aires has b...,NaN,2015-02-22 12:08:04 -0800,"Buenos Aires, Argentina",Buenos Aires
14634,569587691626622976,negative,0.6684,Late Flight,0.6684,American,NaN,GolfWithWoody,NaN,0,@AmericanAir right on cue with the delays👌,NaN,2015-02-22 12:01:02 -0800,NaN,Quito

## 6. Simple String Operations

### Question 29
Display all tweets whose **text** contains the word `thank` (ignore upper and lower case using `case=False`).

In [34]:
df['text'].str.contains('thank',case=False)

0        False
1        False
2        False
3        False
4        False
         ...
14635     True
14636    False
14637    False
14638    False
14639    False
Name: text, Length: 14640, dtype: bool

### Question 30
Count how many tweets contain the word `delay` using `str.contains()` (with `case=False`) and `sum()`.

In [35]:
df['text'].str.contains('delay', case=False, na=False).sum()

np.int64(960)

### Question 31
Convert the values in the **text** column to lowercase using a Pandas string method and display the first 5 results.

In [36]:
df['text'].str.upper().head()

0                  @VIRGINAMERICA WHAT @DHEPBURN SAID.
1    @VIRGINAMERICA PLUS YOU'VE ADDED COMMERCIALS T...
2    @VIRGINAMERICA I DIDN'T TODAY... MUST MEAN I N...
3    @VIRGINAMERICA IT'S REALLY AGGRESSIVE TO BLAST...
4    @VIRGINAMERICA AND IT'S A REALLY BIG BAD THING...
Name: text, dtype: str

## 7. Creating and Modifying Columns

### Question 32
Create a new column called **text_length** that stores the number of characters in each tweet using `str.len()`.

In [39]:
df['text_length'] = df['text'].str.len()
df

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone,text_length
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),35
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),72
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),71
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),126
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN,63
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN,150
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN,60
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada),135
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN,138

### Question 33
Create a new column called **Tweet Size**. Store `Long` when `text_length` is greater than 100; otherwise store `Short`. Use `apply()` with a `lambda` function.

In [41]:
df['Tweet Size'] = df['text_length'].apply(lambda x:'Long' if x>100 else 'Short')
df

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone,text_length,Tweet Size
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),35,Short
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),72,Short
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),71,Short
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),126,Long
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),55,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN,63,Short
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN,150,Long
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN,60,Short
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada),135,Long
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN,138,Long

### Question 34
Remove the **Tweet Size** column using `drop()`.

In [42]:
df.drop('Tweet Size',axis=1)

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone,text_length
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),35
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),72
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),71
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),126
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN,63
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN,150
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN,60
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada),135
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN,138

### Question 35
Rename the column **airline_sentiment** to **sentiment**.

In [43]:
df.rename(columns={'airline_sentiment' : 'sentiment'})

,tweet_id,sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone,text_length,Tweet Size
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),35,Short
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),72,Short
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),71,Short
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),126,Long
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),55,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN,63,Short
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN,150,Long
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN,60,Short
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada),135,Long
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN,138,Long

## 8. Conversion and Export

### Question 36
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [44]:
df.select_dtypes(include='number')

,tweet_id,airline_sentiment_confidence,negativereason_confidence,retweet_count,text_length
0,570306133677760513,1.0000,NaN,0,35
1,570301130888122368,0.3486,0.0000,0,72
2,570301083672813571,0.6837,NaN,0,71
3,570301031407624196,1.0000,0.7033,0,126
4,570300817074462722,1.0000,1.0000,0,55
...,...,...,...,...,...
14635,569587686496825344,0.3487,0.0000,0,63
14636,569587371693355008,1.0000,1.0000,0,150
14637,569587242672398336,1.0000,NaN,0,60
14638,569587188687634433,1.0000,0.6659,0,135
14639,569587140490866689,0.6771,0.0000,0,138

### Question 37
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [45]:
df.head(10).to_numpy()

array([[570306133677760513, 'neutral', 1.0, nan, nan, 'Virgin America',
        nan, 'cairdin', nan, 0, '@VirginAmerica What @dhepburn said.',
        nan, '2015-02-24 11:35:52 -0800', nan,
        'Eastern Time (US & Canada)', 35, 'Short'],
       [570301130888122368, 'positive', 0.3486, nan, 0.0,
        'Virgin America', nan, 'jnardino', nan, 0,
        "@VirginAmerica plus you've added commercials to the experience... tacky.",
        nan, '2015-02-24 11:15:59 -0800', nan,
        'Pacific Time (US & Canada)', 72, 'Short'],
       [570301083672813571, 'neutral', 0.6837, nan, nan,
        'Virgin America', nan, 'yvonnalynn', nan, 0,
        "@VirginAmerica I didn't today... Must mean I need to take another trip!",
        nan, '2015-02-24 11:15:48 -0800', 'Lets Play',
        'Central Time (US & Canada)', 71, 'Short'],
       [570301031407624196, 'negative', 1.0, 'Bad Flight', 0.7033,
        'Virgin America', nan, 'jnardino', nan, 0,
        '@VirginAmerica it\'s really aggressive to blast obnoxious "entertainment" in your guests\' faces &amp; they have little recourse',
        nan, '2015-02-24 11:15:36 -0800', nan,
        'Pacific Time (US & Canada)', 126, 'Long'],
       [570300817074462722, 'negative', 1.0, "Can't Tell", 1.0,
        'Virgin America', nan, 'jnardino', nan, 0,
        "@VirginAmerica and it's a really big bad thing about it", nan,
        '2015-02-24 11:14:45 -0800', nan, 'Pacific Time (US & Canada)',
        55, 'Short'],
       [570300767074181121, 'negative', 1.0, "Can't Tell", 0.6842,
        'Virgin America', nan, 'jnardino', nan, 0,
        "@VirginAmerica seriously would pay $30 a flight for seats that didn't have this playing.\nit's really the only bad thing about flying VA",
        nan, '2015-02-24 11:14:33 -0800', nan,
        'Pacific Time (US & Canada)', 135, 'Long'],
       [570300616901320704, 'positive', 0.6745, nan, 0.0,
        'Virgin America', nan, 'cjmcginnis', nan, 0,
        '@VirginAmerica yes, nearly every time I fly VX this “ear worm” won’t go away :)',
        nan, '2015-02-24 11:13:57 -0800', 'San Francisco CA',
        'Pacific Time (US & Canada)', 79, 'Short'],
       [570300248553349120, 'neutral', 0.634, nan, nan, 'Virgin America',
        nan, 'pilot', nan, 0,
        '@VirginAmerica Really missed a prime opportunity for Men Without Hats parody, there. https://t.co/mWpG7grEZP',
        nan, '2015-02-24 11:12:29 -0800', 'Los Angeles',
        'Pacific Time (US & Canada)', 108, 'Long'],
       [570299953286942721, 'positive', 0.6559, nan, nan,
        'Virgin America', nan, 'dhepburn', nan, 0,
        "@virginamerica Well, I didn't…but NOW I DO! :-D", nan,
        '2015-02-24 11:11:19 -0800', 'San Diego',
        'Pacific Time (US & Canada)', 47, 'Short'],
       [570295459631263746, 'positive', 1.0, nan, nan, 'Virgin America',
        nan, 'YupitsTate', nan, 0,
        "@VirginAmerica it was amazing, and arrived an hour early. You're too good to me.",
        nan, '2015-02-24 10:53:27 -0800', 'Los Angeles',
        'Eastern Time (US & Canada)', 80, 'Short']], dtype=object)

### Question 38
Convert all column names to uppercase using `columns.str.upper()`.

In [47]:
df.columns = df.columns.str.upper()
df

,TWEET_ID,AIRLINE_SENTIMENT,AIRLINE_SENTIMENT_CONFIDENCE,NEGATIVEREASON,NEGATIVEREASON_CONFIDENCE,AIRLINE,AIRLINE_SENTIMENT_GOLD,NAME,NEGATIVEREASON_GOLD,RETWEET_COUNT,TEXT,TWEET_COORD,TWEET_CREATED,TWEET_LOCATION,USER_TIMEZONE,TEXT_LENGTH,TWEET SIZE
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),35,Short
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),72,Short
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),71,Short
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),126,Long
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),55,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN,63,Short
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN,150,Long
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN,60,Short
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada),135,Long
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN,138,Long

### Question 39
Save only the first **1000 rows** of the DataFrame as a new CSV file named **Airline_Sentiment_Practice_Output.csv** using `to_csv()` without saving the index.

In [48]:
df.head(1000).to_csv('Airline_Sentiment_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.