# Exploratory Data Analysis and Insights on Edible and Poisonous Mushrooms Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **mushrooms.csv** dataset contains physical descriptions of mushrooms (cap, gill, stalk, ring, smell, habitat and more) and whether each mushroom is edible or poisonous. Every value is a single letter code.

**Source:** Kaggle - Mushroom Classification (https://www.kaggle.com/datasets/uciml/mushroom-classification).

The dataset contains:

- **8,124 rows**
- **23 columns (all text columns)**
- **No NaN missing values**, but the `stalk-root` column uses the symbol `?` for unknown values

### Columns in the Dataset

| Column | Description |
|---|---|
| `class` | e = edible, p = poisonous |
| `cap-shape` | b = bell, c = conical, x = convex, f = flat, k = knobbed, s = sunken |
| `cap-surface` | f = fibrous, g = grooves, y = scaly, s = smooth |
| `cap-color` | n = brown, b = buff, c = cinnamon, g = gray, r = green, p = pink, u = purple, e = red, w = white, y = yellow |
| `bruises` | t = bruises, f = no bruises |
| `odor` | a = almond, l = anise, c = creosote, y = fishy, f = foul, m = musty, n = none, p = pungent, s = spicy |
| `gill-size` | b = broad, n = narrow |
| `stalk-root` | b = bulbous, c = club, u = cup, e = equal, z = rhizomorphs, r = rooted, ? = unknown |
| `ring-number` | n = none, o = one, t = two |
| `population` | a = abundant, c = clustered, n = numerous, s = scattered, v = several, y = solitary |
| `habitat` | g = grasses, l = leaves, m = meadows, p = paths, u = urban, w = waste, d = woods |
| Other columns | `gill-attachment`, `gill-spacing`, `gill-color`, `stalk-shape`, `stalk-surface-above-ring`, `stalk-surface-below-ring`, `stalk-color-above-ring`, `stalk-color-below-ring`, `veil-type`, `veil-color`, `ring-type`, `spore-print-color`. Use `df.columns` to see them all |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()` and `to_csv()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **mushrooms.csv** into a DataFrame named `df`.

In [116]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\Mushroom\mushrooms.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [117]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

### Question 3
Display the last **5 rows** of the dataset.

In [118]:
df.tail()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

### Question 4
Find the total number of **rows and columns** in the dataset.

In [119]:
df.shape

(8124, 23)

### Question 5
Display all the **column names** present in the dataset.

In [120]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [121]:
df.dtypes

class                       str
cap-shape                   str
cap-surface                 str
cap-color                   str
bruises                     str
odor                        str
gill-attachment             str
gill-spacing                str
gill-size                   str
gill-color                  str
stalk-shape                 str
stalk-root                  str
stalk-surface-above-ring    str
stalk-surface-below-ring    str
stalk-color-above-ring      str
stalk-color-below-ring      str
veil-type                   str
veil-color                  str
ring-number                 str
ring-type                   str
spore-print-color           str
population                  str
habitat                     str
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   str
 1   cap-shape                 8124 non-null   str
 2   cap-surface               8124 non-null   str
 3   cap-color                 8124 non-null   str
 4   bruises                   8124 non-null   str
 5   odor                      8124 non-null   str
 6   gill-attachment           8124 non-null   str
 7   gill-spacing              8124 non-null   str
 8   gill-size                 8124 non-null   str
 9   gill-color                8124 non-null   str
 10  stalk-shape               8124 non-null   str
 11  stalk-root                8124 non-null   str
 12  stalk-surface-above-ring  8124 non-null   str
 13  stalk-surface-below-ring  8124 non-null   str
 14  stalk-color-above-ring    8124 non-null   str
 15  stalk-color-below-ring    8124 non-null   str
 16  veil-type                 8124 non-null   str
 17  veil-color                8124 non-null   str
 18  ring-number               8124 non-null   str
 19  ring-type                 8124 non-null   str
 20  spore-print-color         8124 non-null   str
 21  population                8124 non-null   str
 22  habitat                   8124 non-null   str
dtypes: str(23)
memory usage: 1.4 MB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [123]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [124]:
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

### Question 10
Count how many rows have the value `?` in the **stalk-root** column (hint: compare the column with `'?'` and use `sum()`).

In [125]:
(df['stalk-root']=='?').sum()

np.int64(2480)

### Question 11
Count the total number of `?` values in the **whole DataFrame** (hint: compare the whole DataFrame with `'?'` and use `sum()` twice).

In [126]:
(df =='?').sum().sum()

np.int64(2480)

## 3. Selecting Data

### Question 12
Select and display only the **class** column.

In [127]:
df['class']

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 8124, dtype: str

### Question 13
Select and display the **class, odor, and habitat** columns.

In [128]:
df[['class','odor','habitat']]

     class odor habitat
0        p    p       u
1        e    a       g
2        e    l       m
3        p    p       u
4        e    n       g
...    ...  ...     ...
8119     e    n       l
8120     e    n       l
8121     e    n       l
8122     p    y       l
8123     e    n       l

[8124 rows x 3 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [129]:
df[0:10]

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
5,e,x,y,y,t,a,f,c,b,n,...,s,w,w,p,w,o,p,k,n,g
6,e,b,s,w,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,n,m
7,e,b,y,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,s,m
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
9,e,b,s,y,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,s,m

### Question 15
Using `iloc`, display the first **5 rows and first 4 columns**.

In [130]:
df.iloc[:5,:4]

  class cap-shape cap-surface cap-color
0     p         x           s         n
1     e         x           s         y
2     e         b           s         w
3     p         x           y         w
4     e         x           s         g

### Question 16
Using `loc`, display rows **0 to 4** for the columns **class, cap-shape, and odor**.

In [131]:
df.loc[0:4,['class','cap-shape','odor']]

  class cap-shape odor
0     p         x    p
1     e         x    a
2     e         b    l
3     p         x    p
4     e         x    n

## 4. Exploring Unique Values

### Question 17
Display all the **unique values** from the **odor** column.

In [132]:
df['odor'].unique()

<StringArray>
['p', 'a', 'l', 'n', 'f', 'c', 'y', 's', 'm']
Length: 9, dtype: str

### Question 18
Find the total number of **unique values** in the **odor** column.

In [133]:
df['odor'].nunique()

9

### Question 19
Display all the **unique values** from the **habitat** column.

In [134]:
df['habitat'].unique()

<StringArray>
['u', 'g', 'm', 'd', 'p', 'w', 'l']
Length: 7, dtype: str

### Question 20
Count how many records belong to each **class** value using `value_counts()`.

In [135]:
df['class'].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

### Question 21
Count how many records belong to each **habitat** value using `value_counts()`.

In [136]:
df['habitat'].value_counts()

habitat
d    3148
g    2148
p    1144
l     832
u     368
m     292
w     192
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 22
Display only the rows where **class** is **p**.

In [137]:
df[df['class']=='p']

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
17,p,x,s,n,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8114,p,f,y,c,f,m,a,c,b,y,...,y,c,c,p,w,n,n,w,c,d
8116,p,k,y,n,f,s,f,c,n,b,...,k,p,w,p,w,o,e,w,v,l
8117,p,k,s,e,f,y,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8118,p,k,y,n,f,f,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l

### Question 23
Display only the rows where **odor** is **n**.

In [138]:
df[df['odor']=='n']

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
14,e,x,f,n,f,n,f,w,b,n,...,f,w,w,p,w,o,e,k,a,g
15,e,s,f,g,f,n,f,c,n,k,...,s,w,w,p,w,o,p,n,y,u
16,e,f,f,w,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
28,e,f,f,n,f,n,f,c,n,k,...,s,w,w,p,w,o,p,k,y,u
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8115,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,v,l
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

### Question 24
Display only the rows where **habitat** is **d**.

In [139]:
df[df['habitat']=='d']

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
29,e,x,s,y,t,a,f,w,n,n,...,s,w,w,p,w,o,p,n,v,d
35,e,x,f,y,t,l,f,w,n,w,...,s,w,w,p,w,o,p,n,v,d
38,e,x,f,y,t,a,f,w,n,p,...,s,w,w,p,w,o,p,n,v,d
70,e,f,f,y,t,l,f,w,n,p,...,s,w,w,p,w,o,p,n,v,d
72,e,f,f,y,t,l,f,w,n,w,...,s,w,w,p,w,o,p,n,v,d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8098,p,k,s,e,f,y,f,c,n,b,...,k,w,p,p,w,o,e,w,v,d
8113,p,k,y,e,f,y,f,c,n,b,...,k,p,p,p,w,o,e,w,v,d
8114,p,f,y,c,f,m,a,c,b,y,...,y,c,c,p,w,n,n,w,c,d
8117,p,k,s,e,f,y,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8118,p,k,y,n,f,f,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d

### Question 25
Using `query()`, display all mushrooms where **odor** is `f`.

In [140]:
df.query('odor=="f"')

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
1816,p,x,f,g,f,f,f,c,b,h,...,k,n,b,p,w,o,l,h,y,g
2128,p,x,f,g,f,f,f,c,b,p,...,k,b,b,p,w,o,l,h,y,g
2178,p,x,f,g,f,f,f,c,b,p,...,k,n,p,p,w,o,l,h,y,d
2238,p,x,f,g,f,f,f,c,b,g,...,k,b,p,p,w,o,l,h,y,p
2385,p,x,f,g,f,f,f,c,b,h,...,k,n,n,p,w,o,l,h,y,d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8087,p,x,s,e,f,f,f,c,n,b,...,s,w,p,p,w,o,e,w,v,p
8089,p,k,y,e,f,f,f,c,n,b,...,k,w,p,p,w,o,e,w,v,d
8090,p,k,s,n,f,f,f,c,n,b,...,s,p,p,p,w,o,e,w,v,d
8091,p,k,y,e,f,f,f,c,n,b,...,k,w,w,p,w,o,e,w,v,p
8118,p,k,y,n,f,f,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d

### Question 26
Display mushrooms that are **edible** (`class` equal to `e`) and have **odor equal to n**.

In [141]:
df.query('`class` == "e" and odor=="n"')

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
14,e,x,f,n,f,n,f,w,b,n,...,f,w,w,p,w,o,e,k,a,g
15,e,s,f,g,f,n,f,c,n,k,...,s,w,w,p,w,o,p,n,y,u
16,e,f,f,w,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
28,e,f,f,n,f,n,f,c,n,k,...,s,w,w,p,w,o,p,k,y,u
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8115,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,v,l
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

### Question 27
Display mushrooms that are **poisonous** (`class` equal to `p`) and have **gill-size equal to n**.

In [142]:
df.query('`class`=="p" and `gill-size`=="n"')

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
17,p,x,s,n,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8113,p,k,y,e,f,y,f,c,n,b,...,k,p,p,p,w,o,e,w,v,d
8116,p,k,y,n,f,s,f,c,n,b,...,k,p,w,p,w,o,e,w,v,l
8117,p,k,s,e,f,y,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8118,p,k,y,n,f,f,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l

## 6. Simple String Operations

### Question 28
Using a Pandas string method on the **column names**, display only the column names that contain the word `stalk`.

In [143]:
df.columns[df.columns.str.contains('stalk')]

Index(['stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring'],
      dtype='str')

### Question 29
Convert the values in the **class** column to uppercase using a Pandas string method and display the result.

In [144]:
df['class'] = df['class'].str.upper()
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,P,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,E,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,E,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,P,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,E,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,E,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,E,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,P,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

## 7. Creating and Modifying Columns

### Question 30
Create a new column called **Edibility**. Store `Edible` when `class` is `e`; otherwise store `Poisonous`. Use `apply()` with a `lambda` function.

In [145]:
df['Edibility'] = df['class'].apply(lambda x:'Edible' if x=='E' else 'Poisonous')
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,Edibility
0,P,x,s,n,t,p,f,c,n,k,...,w,w,p,w,o,p,k,s,u,Poisonous
1,E,x,s,y,t,a,f,c,b,k,...,w,w,p,w,o,p,n,n,g,Edible
2,E,b,s,w,t,l,f,c,b,n,...,w,w,p,w,o,p,n,n,m,Edible
3,P,x,y,w,t,p,f,c,n,n,...,w,w,p,w,o,p,k,s,u,Poisonous
4,E,x,s,g,f,n,f,w,b,k,...,w,w,p,w,o,e,n,a,g,Edible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,E,k,s,n,f,n,a,c,b,y,...,o,o,p,o,o,p,b,c,l,Edible
8120,E,x,s,n,f,n,a,c,b,y,...,o,o,p,n,o,p,b,v,l,Edible
8121,E,f,s,n,f,n,a,c,b,n,...,o,o,p,o,o,p,b,c,l,Edible
8122,P,k,y,n,f,y,f,c,n,b,...,w,w,p,w,o,e,w,v,l,Poisonous
8123,E,x,s,n,f,n,a,c,b,y,...,o,o,p,o,o,p,o,c,l,Edible

### Question 31
Display the first **10 rows** after creating the **Edibility** column.

In [146]:
df.head(10)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,Edibility
0,P,x,s,n,t,p,f,c,n,k,...,w,w,p,w,o,p,k,s,u,Poisonous
1,E,x,s,y,t,a,f,c,b,k,...,w,w,p,w,o,p,n,n,g,Edible
2,E,b,s,w,t,l,f,c,b,n,...,w,w,p,w,o,p,n,n,m,Edible
3,P,x,y,w,t,p,f,c,n,n,...,w,w,p,w,o,p,k,s,u,Poisonous
4,E,x,s,g,f,n,f,w,b,k,...,w,w,p,w,o,e,n,a,g,Edible
5,E,x,y,y,t,a,f,c,b,n,...,w,w,p,w,o,p,k,n,g,Edible
6,E,b,s,w,t,a,f,c,b,g,...,w,w,p,w,o,p,k,n,m,Edible
7,E,b,y,w,t,l,f,c,b,n,...,w,w,p,w,o,p,n,s,m,Edible
8,P,x,y,w,t,p,f,c,n,p,...,w,w,p,w,o,p,k,v,g,Poisonous
9,E,b,s,y,t,a,f,c,b,g,...,w,w,p,w,o,p,k,s,m,Edible

### Question 32
Remove the **Edibility** column using `drop()`.

In [147]:
df.drop('Edibility',axis=1,inplace=True)

### Question 33
Rename the column **class** to **Mushroom_Class**.

In [148]:
df.rename(columns={'class':'Mushroom_Class'},inplace=True)
df

,Mushroom_Class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,P,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,E,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,E,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,P,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,E,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,E,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,E,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,P,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

## 8. Conversion and Export

### Question 34
Select and display only the **text (object) columns** using `select_dtypes()` with `include='object'`.

In [149]:
df.select_dtypes(include='object')

C:\Users\vivek\AppData\Local\Temp\ipykernel_19920\676392701.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object')

,Mushroom_Class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,P,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,E,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,E,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,P,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,E,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,E,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,E,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,P,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

### Question 35
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [151]:
df.head(10).to_numpy()

array([['P', 'x', 's', 'n', 't', 'p', 'f', 'c', 'n', 'k', 'e', 'e', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'u'],
       ['E', 'x', 's', 'y', 't', 'a', 'f', 'c', 'b', 'k', 'e', 'c', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'g'],
       ['E', 'b', 's', 'w', 't', 'l', 'f', 'c', 'b', 'n', 'e', 'c', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'm'],
       ['P', 'x', 'y', 'w', 't', 'p', 'f', 'c', 'n', 'n', 'e', 'e', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'u'],
       ['E', 'x', 's', 'g', 'f', 'n', 'f', 'w', 'b', 'k', 't', 'e', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'e', 'n', 'a', 'g'],
       ['E', 'x', 'y', 'y', 't', 'a', 'f', 'c', 'b', 'n', 'e', 'c', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'n', 'g'],
       ['E', 'b', 's', 'w', 't', 'a', 'f', 'c', 'b', 'g', 'e', 'c', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'n', 'm'],
       ['E', 'b', 'y', 'w', 't', 'l', 'f', 'c', 'b', 'n', 'e', 'c', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'm'],
       ['P', 'x', 'y', 'w', 't', 'p', 'f', 'c', 'n', 'p', 'e', 'e', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'v', 'g'],
       ['E', 'b', 's', 'y', 't', 'a', 'f', 'c', 'b', 'g', 'e', 'c', 's',
        's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'm']], dtype=object)

### Question 36
Replace the hyphens (`-`) in all column names with underscores using `columns.str.replace()`.

In [153]:
df.columns.str.replace('-','_')
df

,Mushroom_Class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,P,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,E,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,E,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,P,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,E,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,E,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,E,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,P,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,E,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

### Question 37
Save only the first **1000 rows** of the DataFrame as a new CSV file named **Mushroom_Practice_Output.csv** using `to_csv()` without saving the index.

In [154]:
df.head(1000).to_csv('Mushroom_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.