# Exploratory Data Analysis and Insights on Mall Customer Segmentation Data Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **Mall_Customers.csv** dataset contains basic details of customers of a shopping mall, along with their yearly income and a spending score given by the mall.

**Source:** Kaggle - Customer Segmentation Tutorial in Python (https://www.kaggle.com/datasets/vjchoudhary7/customer-segmentation-tutorial-in-python).

The dataset contains:

- **200 rows**
- **5 columns**
- **No missing values were found during the initial dataset review**

### Columns in the Dataset

| Column | Description |
|---|---|
| `CustomerID` | Unique ID of the customer |
| `Genre` | Gender of the customer (Male / Female) |
| `Age` | Age of the customer |
| `Annual Income (k$)` | Annual income in thousands of dollars |
| `Spending Score (1-100)` | Score given by the mall based on customer spending behaviour |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()` and `to_csv()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **Mall_Customers.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\Mall_Customers\Mall_Customers.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

### Question 3
Display the last **5 rows** of the dataset.

In [3]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

### Question 4
Find the total number of **rows and columns** in the dataset.

In [4]:
df.shape

(200, 5)

### Question 5
Display all the **column names** present in the dataset.

In [5]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [6]:
df.dtypes

CustomerID                int64
Gender                      str
Age                       int64
Annual Income (k$)        int64
Spending Score (1-100)    int64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [8]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [9]:
df.isna().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

## 3. Selecting Data

### Question 10
Select and display only the **Age** column.

In [10]:
df['Age']

0      19
1      21
2      20
3      23
4      31
       ..
195    35
196    45
197    32
198    32
199    30
Name: Age, Length: 200, dtype: int64

### Question 11
Select and display the **Genre, Age, and Annual Income (k$)** columns.

In [13]:
df[['Gender','Age','Annual Income (k$)']]

     Gender  Age  Annual Income (k$)
0      Male   19                  15
1      Male   21                  15
2    Female   20                  16
3    Female   23                  16
4    Female   31                  17
..      ...  ...                 ...
195  Female   35                 120
196  Female   45                 126
197    Male   32                 126
198    Male   32                 137
199    Male   30                 137

[200 rows x 3 columns]

### Question 12
Display the first **10 rows** using DataFrame slicing.

In [14]:
df.loc[0:10]

    CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0            1    Male   19                  15                      39
1            2    Male   21                  15                      81
2            3  Female   20                  16                       6
3            4  Female   23                  16                      77
4            5  Female   31                  17                      40
5            6  Female   22                  17                      76
6            7  Female   35                  18                       6
7            8  Female   23                  18                      94
8            9    Male   64                  19                       3
9           10  Female   30                  19                      72
10          11    Male   67                  19                      14

### Question 13
Using `iloc`, display the first **5 rows and first 4 columns**.

In [15]:
df.iloc[:5,:4]

   CustomerID  Gender  Age  Annual Income (k$)
0           1    Male   19                  15
1           2    Male   21                  15
2           3  Female   20                  16
3           4  Female   23                  16
4           5  Female   31                  17

### Question 14
Using `loc`, display rows **0 to 4** for the columns **CustomerID, Genre, and Age**.

In [16]:
df.loc[0:4,['CustomerID','Gender','Age']]

   CustomerID  Gender  Age
0           1    Male   19
1           2    Male   21
2           3  Female   20
3           4  Female   23
4           5  Female   31

## 4. Exploring Unique Values

### Question 15
Display all the **unique values** from the **Genre** column.

In [17]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

### Question 16
Find the total number of **unique values** in the **Genre** column.

In [18]:
df['Gender'].nunique()

2

### Question 17
Display all the **unique values** from the **Age** column.

In [19]:
df['Age'].unique()

array([19, 21, 20, 23, 31, 22, 35, 64, 30, 67, 58, 24, 37, 52, 25, 46, 54,
       29, 45, 40, 60, 53, 18, 49, 42, 36, 65, 48, 50, 27, 33, 59, 47, 51,
       69, 70, 63, 43, 68, 32, 26, 57, 38, 55, 34, 66, 39, 44, 28, 56, 41])

### Question 18
Count how many records belong to each **Genre** value using `value_counts()`.

In [21]:
df['Gender'].value_counts()

Gender
Female    112
Male       88
Name: count, dtype: int64

### Question 19
Count how many customers belong to each **Age** value using `value_counts()`.

In [22]:
df['Age'].value_counts()

Age
32    11
35     9
19     8
31     8
30     7
49     7
23     6
40     6
36     6
27     6
47     6
38     6
21     5
20     5
29     5
48     5
50     5
34     5
67     4
24     4
54     4
18     4
59     4
28     4
22     3
37     3
25     3
46     3
45     3
60     3
33     3
43     3
68     3
39     3
58     2
52     2
53     2
42     2
65     2
51     2
70     2
63     2
26     2
57     2
66     2
44     2
41     2
64     1
69     1
55     1
56     1
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 20
Find the **maximum value** available in the **Annual Income (k$)** column.

In [23]:
df['Annual Income (k$)'].max()

np.int64(137)

### Question 21
Display all rows whose **Annual Income (k$)** is greater than **100**.

In [24]:
df[df['Annual Income (k$)']>100]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

### Question 22
Display all rows whose **Spending Score (1-100)** is greater than **80**.

In [26]:
df[df['Spending Score (1-100)']>80]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
1             2    Male   21                  15                      81
7             8  Female   23                  18                      94
11           12  Female   35                  19                      99
19           20  Female   35                  23                      98
25           26    Male   29                  28                      82
29           30  Female   23                  29                      87
33           34    Male   18                  33                      92
35           36  Female   21                  33                      81
41           42    Male   24                  38                      92
123         124    Male   39                  69                      91
127         128    Male   40                  71                      95
135         136  Female   29                  73                      88
141         142    Male   32                  75                      93
143         144  Female   32                  76                      87
145         146    Male   28                  77                      97
149         150    Male   34                  78                      90
151         152    Male   39                  78                      88
155         156  Female   27                  78                      89
161         162  Female   29                  79                      83
163         164  Female   31                  81                      93
167         168  Female   33                  86                      95
173         174    Male   36                  87                      92
175         176  Female   30                  88                      86
179         180    Male   35                  93                      90
181         182  Female   32                  97                      86
183         184  Female   29                  98                      88
185         186    Male   30                  99                      97
189         190  Female   36                 103                      85
193         194  Female   38                 113                      91
199         200    Male   30                 137                      83

### Question 23
Display only the rows where **Genre** is **Female**.

In [27]:
df[df['Gender']=='Female']

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
..          ...     ...  ...                 ...                     ...
191         192  Female   32                 103                      69
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28

[112 rows x 5 columns]

### Question 24
Using `query()`, display all customers whose **Age** is greater than 50.

In [29]:
df.query('Age >50')

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
8             9    Male   64                  19                       3
10           11    Male   67                  19                      14
12           13  Female   58                  20                      15
18           19    Male   52                  23                      29
24           25  Female   54                  28                      14
30           31    Male   60                  30                       4
32           33    Male   53                  33                       4
40           41  Female   65                  38                      35
53           54    Male   59                  43                      60
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
67           68  Female   68                  48                      48
70           71    Male   70                  49                      55
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
80           81    Male   57                  54                      51
82           83    Male   67                  54                      41
86           87  Female   55                  57                      58
90           91  Female   68                  59                      55
102         103    Male   67                  62                      59
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
116         117  Female   63                  65                      43
118         119  Female   51                  67                      43
128         129    Male   59                  71                      11
140         141  Female   57                  75                       5
160         161  Female   56                  79                      35
174         175  Female   52                  88                      13
176         177    Male   58                  88                      15
178         179    Male   59                  93                      14
186         187  Female   54                 101                      24

### Question 25
Display customers having **Annual Income (k$) greater than 70** and **Spending Score (1-100) greater than 70**.

In [31]:
df.query('`Annual Income (k$)` >70 and `Spending Score (1-100)` >70')

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
127         128    Male   40                  71                      95
129         130    Male   38                  71                      75
131         132    Male   39                  71                      75
133         134  Female   31                  72                      71
135         136  Female   29                  73                      88
137         138    Male   32                  73                      73
139         140  Female   35                  74                      72
141         142    Male   32                  75                      93
143         144  Female   32                  76                      87
145         146    Male   28                  77                      97
147         148  Female   32                  77                      74
149         150    Male   34                  78                      90
151         152    Male   39                  78                      88
153         154  Female   38                  78                      76
155         156  Female   27                  78                      89
157         158  Female   30                  78                      78
159         160  Female   30                  78                      73
161         162  Female   29                  79                      83
163         164  Female   31                  81                      93
165         166  Female   36                  85                      75
167         168  Female   33                  86                      95
171         172    Male   28                  87                      75
173         174    Male   36                  87                      92
175         176  Female   30                  88                      86
179         180    Male   35                  93                      90
181         182  Female   32                  97                      86
183         184  Female   29                  98                      88
185         186    Male   30                  99                      97
189         190  Female   36                 103                      85
193         194  Female   38                 113                      91
195         196  Female   35                 120                      79
197         198    Male   32                 126                      74
199         200    Male   30                 137                      83

## 6. Simple String Operations

### Question 26
Display all rows where the **Genre** starts with the letter `F`.

In [33]:
df[df['Gender'].str.startswith('F')]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
..          ...     ...  ...                 ...                     ...
191         192  Female   32                 103                      69
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28

[112 rows x 5 columns]

### Question 27
Convert the values in the **Genre** column to uppercase using a Pandas string method and display the result.

In [36]:
df['Gender']=df['Gender'].str.upper()
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    MALE   19                  15                      39
1             2    MALE   21                  15                      81
2             3  FEMALE   20                  16                       6
3             4  FEMALE   23                  16                      77
4             5  FEMALE   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  FEMALE   35                 120                      79
196         197  FEMALE   45                 126                      28
197         198    MALE   32                 126                      74
198         199    MALE   32                 137                      18
199         200    MALE   30                 137                      83

[200 rows x 5 columns]

## 7. Creating and Modifying Columns

### Question 28
Create a new column called **Spending Level**. Store `High` when `Spending Score (1-100)` is greater than 50; otherwise store `Low`. Use `apply()` with a `lambda` function.

In [37]:
df['Spending Level'] = df['Spending Score (1-100)'].apply(lambda x:'High' if x>50 else 'Low')
df

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Spending Level
0,1,MALE,19,15,39,Low
1,2,MALE,21,15,81,High
2,3,FEMALE,20,16,6,Low
3,4,FEMALE,23,16,77,High
4,5,FEMALE,31,17,40,Low
...,...,...,...,...,...,...
195,196,FEMALE,35,120,79,High
196,197,FEMALE,45,126,28,Low
197,198,MALE,32,126,74,High
198,199,MALE,32,137,18,Low
199,200,MALE,30,137,83,High

### Question 29
Display the first **10 rows** after creating the **Spending Level** column.

In [38]:
df.head(10)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Spending Level
0,1,MALE,19,15,39,Low
1,2,MALE,21,15,81,High
2,3,FEMALE,20,16,6,Low
3,4,FEMALE,23,16,77,High
4,5,FEMALE,31,17,40,Low
5,6,FEMALE,22,17,76,High
6,7,FEMALE,35,18,6,Low
7,8,FEMALE,23,18,94,High
8,9,MALE,64,19,3,Low
9,10,FEMALE,30,19,72,High

### Question 30
Remove the **Spending Level** column using `drop()`.

In [40]:
df.drop('Spending Level',axis=1)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    MALE   19                  15                      39
1             2    MALE   21                  15                      81
2             3  FEMALE   20                  16                       6
3             4  FEMALE   23                  16                      77
4             5  FEMALE   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  FEMALE   35                 120                      79
196         197  FEMALE   45                 126                      28
197         198    MALE   32                 126                      74
198         199    MALE   32                 137                      18
199         200    MALE   30                 137                      83

[200 rows x 5 columns]

### Question 31
Rename the column **Annual Income (k$)** to **Annual_Income**.

In [41]:
df.rename(columns={'Annual Income (k$)':'Annual_Income'})

,CustomerID,Gender,Age,Annual_Income,Spending Score (1-100),Spending Level
0,1,MALE,19,15,39,Low
1,2,MALE,21,15,81,High
2,3,FEMALE,20,16,6,Low
3,4,FEMALE,23,16,77,High
4,5,FEMALE,31,17,40,Low
...,...,...,...,...,...,...
195,196,FEMALE,35,120,79,High
196,197,FEMALE,45,126,28,Low
197,198,MALE,32,126,74,High
198,199,MALE,32,137,18,Low
199,200,MALE,30,137,83,High

## 8. Conversion and Export

### Question 32
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [42]:
df.select_dtypes(include='number')

     CustomerID  Age  Annual Income (k$)  Spending Score (1-100)
0             1   19                  15                      39
1             2   21                  15                      81
2             3   20                  16                       6
3             4   23                  16                      77
4             5   31                  17                      40
..          ...  ...                 ...                     ...
195         196   35                 120                      79
196         197   45                 126                      28
197         198   32                 126                      74
198         199   32                 137                      18
199         200   30                 137                      83

[200 rows x 4 columns]

### Question 33
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [43]:
df.head(10).to_numpy()

array([[1, 'MALE', 19, 15, 39, 'Low'],
       [2, 'MALE', 21, 15, 81, 'High'],
       [3, 'FEMALE', 20, 16, 6, 'Low'],
       [4, 'FEMALE', 23, 16, 77, 'High'],
       [5, 'FEMALE', 31, 17, 40, 'Low'],
       [6, 'FEMALE', 22, 17, 76, 'High'],
       [7, 'FEMALE', 35, 18, 6, 'Low'],
       [8, 'FEMALE', 23, 18, 94, 'High'],
       [9, 'MALE', 64, 19, 3, 'Low'],
       [10, 'FEMALE', 30, 19, 72, 'High']], dtype=object)

### Question 34
Replace spaces in all column names with underscores using `columns.str.replace()`.

In [45]:
df.columns = df.columns.str.replace(' ','_')
df

,CustomerID,Gender,Age,Annual_Income_(k$),Spending_Score_(1-100),Spending_Level
0,1,MALE,19,15,39,Low
1,2,MALE,21,15,81,High
2,3,FEMALE,20,16,6,Low
3,4,FEMALE,23,16,77,High
4,5,FEMALE,31,17,40,Low
...,...,...,...,...,...,...
195,196,FEMALE,35,120,79,High
196,197,FEMALE,45,126,28,Low
197,198,MALE,32,126,74,High
198,199,MALE,32,137,18,Low
199,200,MALE,30,137,83,High

### Question 35
Save the DataFrame as a new CSV file named **Mall_Customers_Practice_Output.csv** using `to_csv()` without saving the index.

In [46]:
df.to_csv('Mall_Customers_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.