# Exploratory Data Analysis and Insights on California Housing Prices Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **housing.csv** dataset contains summary information about housing districts in California from the 1990 census, along with the median house value of each district.

**Source:** Kaggle - California Housing Prices (https://www.kaggle.com/datasets/camnugent/california-housing-prices).

The dataset contains:

- **20,640 rows**
- **10 columns**
- **Missing values are present** only in the `total_bedrooms` column (207 values)

### Columns in the Dataset

| Column | Description |
|---|---|
| `longitude` | How far west the district is (a higher value is farther west) |
| `latitude` | How far north the district is (a higher value is farther north) |
| `housing_median_age` | Median age of the houses in the district |
| `total_rooms` | Total number of rooms in the district |
| `total_bedrooms` | Total number of bedrooms in the district |
| `population` | Number of people living in the district |
| `households` | Number of households in the district |
| `median_income` | Median income of the households (in tens of thousands of dollars) |
| `median_house_value` | Median house value in dollars |
| `ocean_proximity` | Distance from the ocean (`<1H OCEAN`, `INLAND`, `ISLAND`, `NEAR BAY`, `NEAR OCEAN`) |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()`, `to_csv()`, `fillna()`, `median()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **housing.csv** into a DataFrame named `df`.

In [74]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\Housing\housing.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [75]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

### Question 3
Display the last **5 rows** of the dataset.

In [76]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

### Question 4
Find the total number of **rows and columns** in the dataset.

In [77]:
df.shape

(20640, 10)

### Question 5
Display all the **column names** present in the dataset.

In [78]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [79]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [81]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [82]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 10
Find the **percentage of missing values** in the **total_bedrooms** column.

In [83]:
df['total_bedrooms'].isna().mean() * 100

np.float64(1.002906976744186)

### Question 11
Fill the missing values in **total_bedrooms** with the **median** of that column using `fillna()` and `median()`, then check the missing values again.

In [84]:
df['total_bedrooms']=df['total_bedrooms'].isna().fillna(df['total_bedrooms'].median())
df['total_bedrooms'].isna().sum()

np.int64(0)

## 3. Selecting Data

### Question 12
Select and display only the **median_house_value** column.

In [85]:
df['median_house_value']

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

### Question 13
Select and display the **longitude, latitude, and median_house_value** columns.

In [86]:
df[['longitude','latitude','median_house_value',]]

       longitude  latitude  median_house_value
0        -122.23     37.88            452600.0
1        -122.22     37.86            358500.0
2        -122.24     37.85            352100.0
3        -122.25     37.85            341300.0
4        -122.25     37.85            342200.0
...          ...       ...                 ...
20635    -121.09     39.48             78100.0
20636    -121.21     39.49             77100.0
20637    -121.22     39.43             92300.0
20638    -121.32     39.43             84700.0
20639    -121.24     39.37             89400.0

[20640 rows x 3 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [87]:
df.loc[0:10]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,False,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,False,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,False,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,False,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,False,1551.0,714.0,3.6912,261100.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,False,910.0,402.0,3.2031,281500.0,NEAR BAY

### Question 15
Using `iloc`, display the first **5 rows and first 4 columns**.

In [88]:
df.iloc[:5,:4]

   longitude  latitude  housing_median_age  total_rooms
0    -122.23     37.88                41.0        880.0
1    -122.22     37.86                21.0       7099.0
2    -122.24     37.85                52.0       1467.0
3    -122.25     37.85                52.0       1274.0
4    -122.25     37.85                52.0       1627.0

### Question 16
Using `loc`, display rows **0 to 4** for the columns **housing_median_age, total_rooms, and median_income**.

In [89]:
df.loc[0:4,['housing_median_age','total_rooms','median_income']]

   housing_median_age  total_rooms  median_income
0                41.0        880.0         8.3252
1                21.0       7099.0         8.3014
2                52.0       1467.0         7.2574
3                52.0       1274.0         5.6431
4                52.0       1627.0         3.8462

## 4. Exploring Unique Values

### Question 17
Display all the **unique values** from the **ocean_proximity** column.

In [90]:
df['ocean_proximity'].unique()

<StringArray>
['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND']
Length: 5, dtype: str

### Question 18
Find the total number of **unique values** in the **ocean_proximity** column.

In [91]:
df['ocean_proximity'].nunique()

5

### Question 19
Count how many records belong to each **ocean_proximity** value using `value_counts()`.

In [92]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

### Question 20
Find the total number of **unique values** in the **housing_median_age** column.

In [93]:
df['housing_median_age'].nunique()

52

### Question 21
Display the **5 most common** values of **housing_median_age** using `value_counts()` and `head()`.

In [94]:
df['housing_median_age'].value_counts().head()

housing_median_age
52.0    1273
36.0     862
35.0     824
16.0     771
17.0     698
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 22
Find the **maximum value** available in the **median_house_value** column.

In [95]:
df['median_house_value'].max()

np.float64(500001.0)

### Question 23
Find the **minimum value** available in the **median_income** column.

In [96]:
df['median_income'].min()

np.float64(0.4999)

### Question 24
Display all rows whose **median_house_value** is greater than **400000**.

In [97]:
df[df['median_house_value']>400000]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY
89,-122.27,37.80,52.0,249.0,False,396.0,85.0,1.2434,500001.0,NEAR BAY
128,-122.21,37.83,40.0,4991.0,False,1616.0,654.0,7.5544,411500.0,NEAR BAY
140,-122.18,37.81,30.0,292.0,False,126.0,52.0,6.3624,483300.0,NEAR BAY
155,-122.23,37.81,52.0,2315.0,False,861.0,258.0,8.8793,410300.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20428,-118.83,34.23,6.0,8803.0,False,3385.0,1010.0,8.7288,425800.0,<1H OCEAN
20436,-118.69,34.21,10.0,3663.0,False,1179.0,371.0,12.5420,500001.0,<1H OCEAN
20438,-118.79,34.26,17.0,1986.0,False,761.0,241.0,7.2137,401900.0,<1H OCEAN
20442,-118.78,34.25,13.0,1841.0,False,833.0,231.0,7.7785,404700.0,<1H OCEAN
20443,-118.85,34.27,50.0,187.0,False,130.0,35.0,3.3438,500001.0,<1H OCEAN

### Question 25
Display all rows whose **total_rooms** is greater than **10000**.

In [98]:
df[df['total_rooms']>10000]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
283,-122.16,37.79,22.0,12842.0,False,4985.0,1967.0,5.9849,371000.0,NEAR BAY
570,-122.24,37.72,5.0,18634.0,False,7427.0,2718.0,7.6110,350700.0,NEAR BAY
576,-122.06,37.77,12.0,14316.0,False,5781.0,2007.0,7.2634,341600.0,NEAR BAY
864,-122.01,37.57,14.0,16199.0,False,8117.0,2847.0,5.8322,281800.0,NEAR BAY
865,-122.04,37.58,14.0,14917.0,False,8012.0,2606.0,5.6277,269800.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20451,-118.90,34.26,5.0,25187.0,False,11956.0,3478.0,6.9712,321300.0,<1H OCEAN
20529,-121.78,38.55,12.0,10509.0,False,5633.0,2138.0,2.9605,204300.0,INLAND
20530,-121.76,38.57,11.0,15018.0,False,7984.0,2962.0,3.1371,201800.0,INLAND
20563,-121.75,38.67,9.0,12139.0,False,6837.0,2358.0,3.1250,132500.0,INLAND
20629,-121.39,39.12,28.0,10035.0,False,6912.0,1818.0,2.0943,108300.0,INLAND

### Question 26
Display only the rows where **ocean_proximity** is **ISLAND**.

In [99]:
df[df['ocean_proximity']=='ISLAND']

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
8314,-118.32,33.35,27.0,1675.0,False,744.0,331.0,2.1579,450000.0,ISLAND
8315,-118.33,33.34,52.0,2359.0,False,1100.0,431.0,2.8333,414700.0,ISLAND
8316,-118.32,33.33,52.0,2127.0,False,733.0,288.0,3.3906,300000.0,ISLAND
8317,-118.32,33.34,52.0,996.0,False,341.0,160.0,2.7361,450000.0,ISLAND
8318,-118.48,33.43,29.0,716.0,False,422.0,173.0,2.6042,287500.0,ISLAND

### Question 27
Using `query()`, display all districts having **housing_median_age equal to 52**.

In [100]:
df.query('housing_median_age == 52')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,False,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,False,1094.0,514.0,3.6591,299200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20142,-119.06,34.36,52.0,1239.0,False,934.0,298.0,1.8618,183300.0,<1H OCEAN
20220,-119.27,34.28,52.0,2239.0,False,941.0,397.0,4.1250,349000.0,NEAR OCEAN
20236,-119.27,34.27,52.0,459.0,False,276.0,107.0,2.3750,198400.0,NEAR OCEAN
20237,-119.27,34.27,52.0,1577.0,False,836.0,335.0,3.5893,206600.0,NEAR OCEAN
20592,-121.58,39.14,52.0,662.0,False,520.0,149.0,0.8928,55000.0,INLAND

### Question 28
Display districts having **median_income greater than 8** and **ocean_proximity equal to NEAR BAY**.

In [101]:
df.query('median_income >8 and ocean_proximity=="NEAR BAY"')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY
131,-122.19,37.84,18.0,1617.0,False,533.0,194.0,11.6017,392600.0,NEAR BAY
134,-122.19,37.83,28.0,1326.0,False,463.0,190.0,8.2049,335200.0,NEAR BAY
135,-122.20,37.83,26.0,1589.0,False,542.0,211.0,8.4010,351200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
18358,-122.10,37.36,35.0,2063.0,False,676.0,252.0,8.5294,500001.0,NEAR BAY
18360,-122.09,37.35,30.0,1502.0,False,501.0,180.0,10.0259,500001.0,NEAR BAY
18361,-122.14,37.36,23.0,11294.0,False,3840.0,1367.0,12.1387,500001.0,NEAR BAY
18362,-122.15,37.35,23.0,3814.0,False,1344.0,464.0,12.9792,500001.0,NEAR BAY
18934,-122.18,38.29,18.0,1953.0,False,658.0,270.0,8.0113,393000.0,NEAR BAY

## 6. Simple String Operations

### Question 29
Display all districts where **ocean_proximity** contains the word `OCEAN`.

In [102]:
df[df['ocean_proximity'].str.contains('OCEAN', case=False, na=False)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
701,-121.97,37.64,32.0,1283.0,False,485.0,171.0,6.0574,431000.0,<1H OCEAN
830,-121.99,37.61,9.0,3666.0,False,2341.0,703.0,4.6458,217000.0,<1H OCEAN
859,-121.97,37.57,21.0,4342.0,False,2172.0,789.0,4.6146,247600.0,<1H OCEAN
860,-121.96,37.58,15.0,3575.0,False,1777.0,559.0,5.7192,283500.0,<1H OCEAN
861,-121.98,37.58,20.0,4126.0,False,2079.0,975.0,3.6832,216900.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
20502,-118.68,34.33,45.0,121.0,False,67.0,27.0,2.9821,325000.0,<1H OCEAN
20503,-118.75,34.33,27.0,534.0,False,243.0,77.0,8.2787,330000.0,<1H OCEAN
20504,-118.73,34.29,11.0,5451.0,False,2526.0,752.0,7.3550,343900.0,<1H OCEAN
20505,-118.72,34.29,22.0,3266.0,False,1595.0,494.0,6.0368,248000.0,<1H OCEAN
20506,-118.73,34.29,8.0,4983.0,False,2510.0,725.0,6.9454,276500.0,<1H OCEAN

### Question 30
Convert the values in the **ocean_proximity** column to lowercase using a Pandas string method and display the result.

In [103]:
df['ocean_proximity'].str.lower()
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,False,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,False,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,False,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,False,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,False,1387.0,530.0,2.3886,89400.0,INLAND

## 7. Creating and Modifying Columns

### Question 31
Create a new column called **rooms_per_household** by dividing **total_rooms** by **households**.

In [104]:
df['rooms_per_household'] = df['total_rooms']/df['households']
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853
...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,False,845.0,330.0,1.5603,78100.0,INLAND,5.045455
20636,-121.21,39.49,18.0,697.0,False,356.0,114.0,2.5568,77100.0,INLAND,6.114035
20637,-121.22,39.43,17.0,2254.0,False,1007.0,433.0,1.7000,92300.0,INLAND,5.205543
20638,-121.32,39.43,18.0,1860.0,False,741.0,349.0,1.8672,84700.0,INLAND,5.329513
20639,-121.24,39.37,16.0,2785.0,False,1387.0,530.0,2.3886,89400.0,INLAND,5.254717

### Question 32
Create a new column called **Price Category**. Store `Expensive` when `median_house_value` is greater than 250000; otherwise store `Affordable`. Use `apply()` with a `lambda` function.

In [105]:
df['Price Category'] = df['median_house_value'].apply(lambda x:'Expensive' if x>250000 else 'Affordable')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,Price Category
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,Expensive
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,Expensive
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,Expensive
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,Expensive
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,False,845.0,330.0,1.5603,78100.0,INLAND,5.045455,Affordable
20636,-121.21,39.49,18.0,697.0,False,356.0,114.0,2.5568,77100.0,INLAND,6.114035,Affordable
20637,-121.22,39.43,17.0,2254.0,False,1007.0,433.0,1.7000,92300.0,INLAND,5.205543,Affordable
20638,-121.32,39.43,18.0,1860.0,False,741.0,349.0,1.8672,84700.0,INLAND,5.329513,Affordable
20639,-121.24,39.37,16.0,2785.0,False,1387.0,530.0,2.3886,89400.0,INLAND,5.254717,Affordable

### Question 33
Remove the **Price Category** column using `drop()`.

In [106]:
df.drop('Price Category',axis=1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853
...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,False,845.0,330.0,1.5603,78100.0,INLAND,5.045455
20636,-121.21,39.49,18.0,697.0,False,356.0,114.0,2.5568,77100.0,INLAND,6.114035
20637,-121.22,39.43,17.0,2254.0,False,1007.0,433.0,1.7000,92300.0,INLAND,5.205543
20638,-121.32,39.43,18.0,1860.0,False,741.0,349.0,1.8672,84700.0,INLAND,5.329513
20639,-121.24,39.37,16.0,2785.0,False,1387.0,530.0,2.3886,89400.0,INLAND,5.254717

### Question 34
Rename the column **median_house_value** to **House_Value**.

In [114]:
df.rename(columns={'median_house_value':'House_value'},inplace=True)
df

,LONGITUDE,LATITUDE,HOUSING_MEDIAN_AGE,TOTAL_ROOMS,TOTAL_BEDROOMS,POPULATION,HOUSEHOLDS,MEDIAN_INCOME,MEDIAN_HOUSE_VALUE,OCEAN_PROXIMITY,ROOMS_PER_HOUSEHOLD,PRICE CATEGORY
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,Expensive
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,Expensive
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,Expensive
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,Expensive
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,False,845.0,330.0,1.5603,78100.0,INLAND,5.045455,Affordable
20636,-121.21,39.49,18.0,697.0,False,356.0,114.0,2.5568,77100.0,INLAND,6.114035,Affordable
20637,-121.22,39.43,17.0,2254.0,False,1007.0,433.0,1.7000,92300.0,INLAND,5.205543,Affordable
20638,-121.32,39.43,18.0,1860.0,False,741.0,349.0,1.8672,84700.0,INLAND,5.329513,Affordable
20639,-121.24,39.37,16.0,2785.0,False,1387.0,530.0,2.3886,89400.0,INLAND,5.254717,Affordable

## 8. Conversion and Export

### Question 35
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [108]:
df.select_dtypes(include='number')

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,rooms_per_household
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,452600.0,6.984127
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,358500.0,6.238137
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,352100.0,8.288136
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,341300.0,5.817352
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,342200.0,6.281853
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,845.0,330.0,1.5603,78100.0,5.045455
20636,-121.21,39.49,18.0,697.0,356.0,114.0,2.5568,77100.0,6.114035
20637,-121.22,39.43,17.0,2254.0,1007.0,433.0,1.7000,92300.0,5.205543
20638,-121.32,39.43,18.0,1860.0,741.0,349.0,1.8672,84700.0,5.329513
20639,-121.24,39.37,16.0,2785.0,1387.0,530.0,2.3886,89400.0,5.254717

### Question 36
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [109]:
df.head(10).to_numpy()

array([[-122.23, 37.88, 41.0, 880.0, False, 322.0, 126.0, 8.3252,
        452600.0, 'NEAR BAY', 6.984126984126984, 'Expensive'],
       [-122.22, 37.86, 21.0, 7099.0, False, 2401.0, 1138.0, 8.3014,
        358500.0, 'NEAR BAY', 6.238137082601054, 'Expensive'],
       [-122.24, 37.85, 52.0, 1467.0, False, 496.0, 177.0, 7.2574,
        352100.0, 'NEAR BAY', 8.288135593220339, 'Expensive'],
       [-122.25, 37.85, 52.0, 1274.0, False, 558.0, 219.0, 5.6431,
        341300.0, 'NEAR BAY', 5.8173515981735155, 'Expensive'],
       [-122.25, 37.85, 52.0, 1627.0, False, 565.0, 259.0, 3.8462,
        342200.0, 'NEAR BAY', 6.281853281853282, 'Expensive'],
       [-122.25, 37.85, 52.0, 919.0, False, 413.0, 193.0, 4.0368,
        269700.0, 'NEAR BAY', 4.761658031088083, 'Expensive'],
       [-122.25, 37.84, 52.0, 2535.0, False, 1094.0, 514.0, 3.6591,
        299200.0, 'NEAR BAY', 4.9319066147859925, 'Expensive'],
       [-122.25, 37.84, 52.0, 3104.0, False, 1157.0, 647.0, 3.12,
        241400.0, 'NEAR BAY', 4.797527047913447, 'Affordable'],
       [-122.26, 37.84, 42.0, 2555.0, False, 1206.0, 595.0, 2.0804,
        226700.0, 'NEAR BAY', 4.294117647058823, 'Affordable'],
       [-122.25, 37.84, 52.0, 3549.0, False, 1551.0, 714.0, 3.6912,
        261100.0, 'NEAR BAY', 4.970588235294118, 'Expensive']],
      dtype=object)

### Question 37
Convert all column names to uppercase using `columns.str.upper()`.

In [112]:
df.columns = df.columns.str.upper()
df

,LONGITUDE,LATITUDE,HOUSING_MEDIAN_AGE,TOTAL_ROOMS,TOTAL_BEDROOMS,POPULATION,HOUSEHOLDS,MEDIAN_INCOME,MEDIAN_HOUSE_VALUE,OCEAN_PROXIMITY,ROOMS_PER_HOUSEHOLD,PRICE CATEGORY
0,-122.23,37.88,41.0,880.0,False,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,Expensive
1,-122.22,37.86,21.0,7099.0,False,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,Expensive
2,-122.24,37.85,52.0,1467.0,False,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,Expensive
3,-122.25,37.85,52.0,1274.0,False,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,Expensive
4,-122.25,37.85,52.0,1627.0,False,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,False,845.0,330.0,1.5603,78100.0,INLAND,5.045455,Affordable
20636,-121.21,39.49,18.0,697.0,False,356.0,114.0,2.5568,77100.0,INLAND,6.114035,Affordable
20637,-121.22,39.43,17.0,2254.0,False,1007.0,433.0,1.7000,92300.0,INLAND,5.205543,Affordable
20638,-121.32,39.43,18.0,1860.0,False,741.0,349.0,1.8672,84700.0,INLAND,5.329513,Affordable
20639,-121.24,39.37,16.0,2785.0,False,1387.0,530.0,2.3886,89400.0,INLAND,5.254717,Affordable

### Question 38
Save only the first **500 rows** of the DataFrame as a new CSV file named **California_Housing_Practice_Output.csv** using `to_csv()` without saving the index.

In [115]:
df.head(500).to_csv('California_Housing_Practice_Output.csv',index=True)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.