# Exploratory Data Analysis and Insights on SMS Spam Messages Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **spam.csv** dataset contains text messages (SMS) that are labelled as either `ham` (normal message) or `spam`.

**Source:** Kaggle - SMS Spam Collection Dataset (https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset).

The dataset contains:

- **5,572 rows**
- **5 columns (2 useful columns and 3 almost empty unnamed columns)**
- **The three unnamed columns contain mostly missing values**; you will remove them in Section 2

### Columns in the Dataset

| Column | Description |
|---|---|
| `v1` | Label of the message (`ham` or `spam`) |
| `v2` | Text of the message |
| `Unnamed: 2`, `Unnamed: 3`, `Unnamed: 4` | Almost empty extra columns created by the file format |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()`, `to_csv()`, `duplicated()`, `str.contains()`, `str.len()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **spam.csv** into a DataFrame named `df`. Use the argument `encoding='latin-1'`, because the file contains special characters that the default encoding cannot read.

In [50]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\SMS_Spam\spam.csv',encoding='latin-1')

### Question 2
Display the first **5 rows** of the dataset.

In [51]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

### Question 3
Display the last **5 rows** of the dataset.

In [52]:
df.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

### Question 4
Find the total number of **rows and columns** in the dataset.

In [53]:
df.shape

(5572, 5)

### Question 5
Display all the **column names** present in the dataset.

In [54]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')

### Question 6
Display the **data type of each column**.

In [55]:
df.dtypes

v1            str
v2            str
Unnamed: 2    str
Unnamed: 3    str
Unnamed: 4    str
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

## 2. Checking Missing Values and Basic Cleaning

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [57]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [58]:
df.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

### Question 10
Remove the three unnamed columns (**Unnamed: 2**, **Unnamed: 3** and **Unnamed: 4**) using `drop()` with `columns=`.

In [59]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'])

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### Question 11
Rename the column **v1** to **label** and the column **v2** to **message**. Use these names in all the questions below.

In [60]:
df = df.rename(columns={'v1':'label','v2':'message'})
df

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

## 3. Selecting Data

### Question 12
Select and display only the **message** column.

In [61]:
df['message']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: str

### Question 13
Select and display the **label and message** columns.

In [62]:
df[['label','message']]

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [63]:
df[0:10]

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
6,ham,Even my brother is not like to speak with me. ...,NaN,NaN,NaN
7,ham,As per your request 'Melle Melle (Oru Minnamin...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN

### Question 15
Using `iloc`, display the first **5 rows and first 2 columns**.

In [64]:
df.iloc[:5,:2]

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Question 16
Using `loc`, display rows **0 to 4** for the columns **label and message**.

In [65]:
df.loc[0:4,['label','message']]

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

## 4. Exploring Unique Values

### Question 17
Display all the **unique values** from the **label** column.

In [66]:
df['label'].unique()

<StringArray>
['ham', 'spam']
Length: 2, dtype: str

### Question 18
Find the total number of **unique values** in the **label** column.

In [67]:
df['label'].nunique()

2

### Question 19
Count how many records belong to each **label** value using `value_counts()`.

In [68]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

### Question 20
Find the total number of **unique values** in the **message** column.

In [69]:
df['message'].nunique()

5169

### Question 21
Find how many **duplicate rows** are present using `duplicated().sum()`.

In [70]:
df.duplicated().sum()

np.int64(403)

## 5. Basic Analysis and Filtering

### Question 22
Find the **maximum message length** (number of characters) using `df['message'].str.len().max()`.

In [71]:
df['message'].str.len().max()

np.int64(910)

### Question 23
Display only the rows where **label** is **spam**.

In [72]:
df[df['label']=='spam']

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN
11,spam,"SIX chances to win CASH! From 100 to 20,000 po...",NaN,NaN,NaN
...,...,...,...,...,...
5537,spam,Want explicit SEX in 30 secs? Ring 02073162414...,NaN,NaN,NaN
5540,spam,ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...,NaN,NaN,NaN
5547,spam,Had your contract mobile 11 Mnths? Latest Moto...,NaN,NaN,NaN
5566,spam,REMINDER FROM O2: To get 2.50 pounds free call...,NaN,NaN,NaN
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN

### Question 24
Using `query()`, display all rows where **label** is `ham`.

In [73]:
df.query('label == "ham"')

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
6,ham,Even my brother is not like to speak with me. ...,NaN,NaN,NaN
...,...,...,...,...,...
5565,ham,Huh y lei...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

### Question 25
Display all messages that are **longer than 150 characters** using `str.len()`.

In [74]:
df[df['message'].str.len() > 150]

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
7,ham,As per your request 'Melle Melle (Oru Minnamin...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN
12,spam,URGENT! You have won a 1 week FREE membership ...,NaN,NaN,NaN
...,...,...,...,...,...
5544,ham,"I'm taking derek &amp; taylor to walmart, if I...",NaN,NaN,NaN
5547,spam,Had your contract mobile 11 Mnths? Latest Moto...,NaN,NaN,NaN
5555,ham,Yeh. Indians was nice. Tho it did kane me off ...,NaN,NaN,NaN
5557,ham,No. I meant the calculation is the same. That ...,NaN,NaN,NaN
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN

### Question 26
Display **spam** messages that are longer than **100 characters**.

In [75]:
df[(df['message']=='spam')&(df['message'].str.len()>100)]

Empty DataFrame
Columns: [label, message, Unnamed: 2, Unnamed: 3, Unnamed: 4]
Index: []

## 6. Simple String Operations

### Question 27
Display all messages that contain the word `free` (ignore upper and lower case using `case=False`).

In [78]:
df[df['message'].str.contains('free',case=False)]

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN
12,spam,URGENT! You have won a 1 week FREE membership ...,NaN,NaN,NaN
42,spam,07732584351 - Rodger Burns - MSG = We tried to...,NaN,NaN,NaN
...,...,...,...,...,...
5492,spam,Marvel Mobile Play the official Ultimate Spide...,NaN,NaN,NaN
5540,spam,ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...,NaN,NaN,NaN
5547,spam,Had your contract mobile 11 Mnths? Latest Moto...,NaN,NaN,NaN
5566,spam,REMINDER FROM O2: To get 2.50 pounds free call...,NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN

### Question 28
Count how many messages contain the text `http` using `str.contains()` and `sum()`.

In [77]:
df['message'].str.contains('http').sum()

np.int64(21)

### Question 29
Convert the values in the **message** column to lowercase using a Pandas string method and display the first 5 results.

In [79]:
df['message'].str.lower().head()

0    go until jurong point, crazy.. available only ...
1                        ok lar... joking wif u oni...
2    free entry in 2 a wkly comp to win fa cup fina...
3    u dun say so early hor... u c already then say...
4    nah i don't think he goes to usf, he lives aro...
Name: message, dtype: str

## 7. Creating and Modifying Columns

### Question 30
Create a new column called **message_length** that stores the number of characters in each message using `str.len()`.

In [80]:
df['message_length'] = df['message'].str.len()
df

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4,message_length
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,111
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,29
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,155
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,49
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,61
...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN,161
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN,37
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN,57
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN,125
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN,26

### Question 31
Create a new column called **Length Category**. Store `Long` when `message_length` is greater than 100; otherwise store `Short`. Use `apply()` with a `lambda` function.

In [82]:
df['Length Category'] = df['message_length'].apply(lambda x:'Long' if x>100 else 'Short')
df

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4,message_length,Length Category
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,111,Long
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,29,Short
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,155,Long
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,49,Short
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,61,Short
...,...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN,161,Long
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN,37,Short
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN,57,Short
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN,125,Long
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN,26,Short

### Question 32
Remove the **Length Category** column using `drop()`.

In [83]:
df.drop('Length Category',axis=1,inplace=True)

### Question 33
Rename the column **message_length** to **msg_len**.

In [85]:
df.rename(columns={'message':'msg_len'})

,label,msg_len,Unnamed: 2,Unnamed: 3,Unnamed: 4,message_length
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,111
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,29
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,155
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,49
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,61
...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN,161
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN,37
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN,57
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN,125
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN,26

## 8. Conversion and Export

### Question 34
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [86]:
df.select_dtypes(include='number')

      message_length
0                111
1                 29
2                155
3                 49
4                 61
...              ...
5567             161
5568              37
5569              57
5570             125
5571              26

[5572 rows x 1 columns]

### Question 35
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [87]:
df.head(10).to_numpy()

array([['ham',
        'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
        nan, nan, nan, 111],
       ['ham', 'Ok lar... Joking wif u oni...', nan, nan, nan, 29],
       ['spam',
        "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
        nan, nan, nan, 155],
       ['ham', 'U dun say so early hor... U c already then say...', nan,
        nan, nan, 49],
       ['ham',
        "Nah I don't think he goes to usf, he lives around here though",
        nan, nan, nan, 61],
       ['spam',
        "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv",
        nan, nan, nan, 148],
       ['ham',
        'Even my brother is not like to speak with me. They treat me like aids patent.',
        nan, nan, nan, 77],
       ['ham',
        "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
        nan, nan, nan, 160],
       ['spam',
        'WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
        nan, nan, nan, 158],
       ['spam',
        'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
        nan, nan, nan, 154]], dtype=object)

### Question 36
Convert all column names to uppercase using `columns.str.upper()`.

In [89]:
df.columns = df.columns.str.upper()
df

,LABEL,MESSAGE,UNNAMED: 2,UNNAMED: 3,UNNAMED: 4,MESSAGE_LENGTH
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,111
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,29
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,155
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,49
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,61
...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN,161
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN,37
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN,57
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN,125
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN,26

### Question 37
Save the DataFrame as a new CSV file named **SMS_Spam_Practice_Output.csv** using `to_csv()` without saving the index.

In [90]:
df.to_csv('SMS_Spam_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.