# Exploratory Data Analysis and Insights on Handwritten Digit Images (MNIST) Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **train.csv** dataset contains images of handwritten digits (0 to 9). Each 28 x 28 pixel image is stored as one row of 784 pixel values, along with the digit it shows.

**Source:** Kaggle - Digit Recognizer (https://www.kaggle.com/c/digit-recognizer). Use the `train.csv` file.

The dataset contains:

- **42,000 rows**
- **785 columns (1 label column and 784 pixel columns)**
- **No missing values were found during the initial dataset review**

### Columns in the Dataset

| Column | Description |
|---|---|
| `label` | The digit shown in the image (0 to 9) |
| `pixel0` to `pixel783` | Brightness of each pixel, from 0 (black) to 255 (white) |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()` and `to_csv()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **train.csv** into a DataFrame named `df`.

In [5]:
import pandas as pd
df = pd.read_csv('D:\\Liha-Tech Assignments\\Pandas\\MNIST_Digit_Recognizer\\train.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [6]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 3
Display the last **5 rows** of the dataset.

In [7]:
df.tail()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 4
Find the total number of **rows and columns** in the dataset.

In [8]:
df.shape

(42000, 785)

### Question 5
Display all the **column names** present in the dataset.

In [9]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='str', length=785)

### Question 6
Display the **data type of each column**.

In [10]:
df.dtypes

label       int64
pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
            ...
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 785, dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [13]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [14]:
df.isna().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

## 3. Selecting Data

### Question 10
Select and display only the **label** column.

In [15]:
df['label']

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

### Question 11
Select and display the **label, pixel0, and pixel1** columns.

In [16]:
df[['label','pixel0','pixel1']]

       label  pixel0  pixel1
0          1       0       0
1          0       0       0
2          1       0       0
3          4       0       0
4          0       0       0
...      ...     ...     ...
41995      0       0       0
41996      1       0       0
41997      7       0       0
41998      6       0       0
41999      9       0       0

[42000 rows x 3 columns]

### Question 12
Display the first **10 rows** using DataFrame slicing.

In [17]:
df.loc[0:10]

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 13
Using `iloc`, display the first **5 rows and first 4 columns**.

In [18]:
df.iloc[:5,:4]

   label  pixel0  pixel1  pixel2
0      1       0       0       0
1      0       0       0       0
2      1       0       0       0
3      4       0       0       0
4      0       0       0       0

### Question 14
Using `loc`, display rows **0 to 4** for the columns **label, pixel150, and pixel300**.

In [19]:
df.loc[0:4,['label','pixel150','pixel300']]

   label  pixel150  pixel300
0      1         0         0
1      0       250       254
2      1         0         0
3      4         0         0
4      0       253       253

## 4. Exploring Unique Values

### Question 15
Display all the **unique values** from the **label** column.

In [20]:
df['label'].unique()

array([1, 0, 4, 7, 3, 5, 8, 9, 2, 6])

### Question 16
Find the total number of **unique values** in the **label** column.

In [21]:
df['label'].nunique()

10

### Question 17
Display all the **unique values** from the **pixel0** column.

In [22]:
df['pixel0'].unique()

array([0])

### Question 18
Count how many records belong to each **label** value using `value_counts()`.

In [23]:
df['label'].value_counts()

label
1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: count, dtype: int64

### Question 19
Count how many images exist for each digit and display the result in digit order (0 to 9) using `value_counts()` and `sort_index()`.

In [24]:
df['label'].value_counts().sort_index()

label
0    4132
1    4684
2    4177
3    4351
4    4072
5    3795
6    4137
7    4401
8    4063
9    4188
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 20
Find the **maximum value** available in the **pixel350** column.

In [25]:
df['pixel350'].max()

np.int64(255)

### Question 21
Display all rows whose **pixel350** is greater than **200**.

In [26]:
df[df['pixel350']>200]

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41990,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41991,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41992,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41993,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 22
Display all rows whose **pixel400** is greater than **100**.

In [27]:
df[df['pixel400']>100]

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41992,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41994,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 23
Display only the rows where **label** is **5**.

In [28]:
df[df['label']==5]

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41928,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41941,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41942,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41987,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41989,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 24
Using `query()`, display all images where **label is 7**.

In [29]:
df.query('label==7')

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
6,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41949,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41957,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41980,7,0,0,0,0,0,0,0,0,0,...,27,253,110,0,0,0,0,0,0,0
41983,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 25
Display images having **label equal to 3** and **pixel350 greater than 100**.

In [30]:
df.query('label==3 and pixel350>100')

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
7,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41955,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41971,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41974,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41985,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41990,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 6. Simple String Operations

### Question 26
Using a Pandas string method on the **column names**, display only the column names that start with `pixel1`.

In [39]:
df.columns.str.startswith('pixel1')

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

### Question 27
Display the **length** of the first 10 column names using `df.columns.str.len()`.

In [43]:
df.columns.str.len()[:10]

Index([5, 5, 4, 5, 5, 5, 5, 5, 5, 5], dtype='int64')

## 7. Creating and Modifying Columns

### Question 28
Create a new column called **Digit Type**. Store `Even` when `label` is an even number; otherwise store `Odd`. Use `apply()` with a `lambda` function.

### Question 29
Display the first **10 rows** after creating the **Digit Type** column.

### Question 30
Remove the **Digit Type** column using `drop()`.

### Question 31
Rename the column **label** to **digit**.

## 8. Conversion and Export

### Question 32
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [44]:
df.select_dtypes(include='number')

,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 33
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [45]:
df.head(10).to_numpy()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [3, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]], shape=(10, 785))

### Question 34
Convert all column names to uppercase using `columns.str.upper()`.

In [47]:
df.columns = df.columns.str.upper()
df

,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Question 35
Save only the first **1000 rows** of the DataFrame as a new CSV file named **MNIST_Practice_Output.csv** using `to_csv()` without saving the index.

In [48]:
df.head(1000).to_csv('MINIST_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.