# Exploratory Data Analysis and Insights on Monthly International Airline Passengers Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **international-airline-passengers.csv** dataset contains the total number of international airline passengers (in thousands) for each month from January 1949 to December 1960. It is a classic small time series dataset.

**Source:** Kaggle - International airline passengers (https://www.kaggle.com/datasets/andreazzini/international-airline-passengers).

The dataset contains:

- **144 monthly records (some copies of the file have one extra text line at the bottom, so check the last rows carefully)**
- **2 columns**
- Missing values depend on the copy of the file. You will check and clean them in Section 2

### Columns in the Dataset

| Column | Description |
|---|---|
| Month column | The month of the record (for example `1949-01`) |
| Passengers column | Total passengers in thousands for that month. The original column name is very long, so you will rename it in Section 2 |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()`, `to_csv()`, `dropna()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **international-airline-passengers.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd
df = pd.read_csv('D:\Liha-Tech Assignments\Pandas\International_Airline_Passengers\international-airline-passengers.csv')

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head()

,Month,International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60
0,1949-01,112.0
1,1949-02,118.0
2,1949-03,132.0
3,1949-04,129.0
4,1949-05,121.0

### Question 3
Display the last **5 rows** of the dataset.

In [ ]:
df.tail()

### Question 4
Find the total number of **rows and columns** in the dataset.

In [3]:
df.shape

(145, 2)

### Question 5
Display all the **column names** present in the dataset.

In [4]:
df.columns

Index(['Month', 'International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60'], dtype='str')

### Question 6
Display the **data type of each column**.

In [5]:
df.dtypes

Month                                                                                 str
International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60    float64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 2 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Month                                                                           145 non-null    str
 1   International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60  144 non-null    float64
dtypes: float64(1), str(1)
memory usage: 2.4 KB

## 2. Checking Missing Values and Renaming Columns

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [7]:
df.isnull().sum()

Month                                                                             0
International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60    1
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [8]:
df.isna().sum()

Month                                                                             0
International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60    1
dtype: int64

### Question 10
Rename the two columns to **Month** and **Passengers** by assigning a new list to `df.columns`. Use these names in all the questions below.

In [10]:
df.columns = ['Month', 'Passengers']
df

                                                 Month  Passengers
0                                              1949-01       112.0
1                                              1949-02       118.0
2                                              1949-03       132.0
3                                              1949-04       129.0
4                                              1949-05       121.0
..                                                 ...         ...
140                                            1960-09       508.0
141                                            1960-10       461.0
142                                            1960-11       390.0
143                                            1960-12       432.0
144  International airline passengers: monthly tota...         NaN

[145 rows x 2 columns]

### Question 11
Remove rows having missing values using `dropna()` and display the new shape of the DataFrame. (If your file has no missing values, the shape will not change.)

In [12]:
df = df.dropna()
df.shape

(144, 2)

## 3. Selecting Data

### Question 12
Select and display only the **Month** column.

In [13]:
df['Month']

0      1949-01
1      1949-02
2      1949-03
3      1949-04
4      1949-05
        ...
139    1960-08
140    1960-09
141    1960-10
142    1960-11
143    1960-12
Name: Month, Length: 144, dtype: str

### Question 13
Select and display the **Month and Passengers** columns.

In [14]:
df[['Month','Passengers']]

       Month  Passengers
0    1949-01       112.0
1    1949-02       118.0
2    1949-03       132.0
3    1949-04       129.0
4    1949-05       121.0
..       ...         ...
139  1960-08       606.0
140  1960-09       508.0
141  1960-10       461.0
142  1960-11       390.0
143  1960-12       432.0

[144 rows x 2 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [15]:
df.loc[0:10]

      Month  Passengers
0   1949-01       112.0
1   1949-02       118.0
2   1949-03       132.0
3   1949-04       129.0
4   1949-05       121.0
5   1949-06       135.0
6   1949-07       148.0
7   1949-08       148.0
8   1949-09       136.0
9   1949-10       119.0
10  1949-11       104.0

### Question 15
Using `iloc`, display the first **5 rows and first 2 columns**.

In [16]:
df.iloc[:5,:2]

     Month  Passengers
0  1949-01       112.0
1  1949-02       118.0
2  1949-03       132.0
3  1949-04       129.0
4  1949-05       121.0

### Question 16
Using `loc`, display rows **0 to 4** for the columns **Month and Passengers**.

In [17]:
df.loc[0:4,['Month','Passengers']]

     Month  Passengers
0  1949-01       112.0
1  1949-02       118.0
2  1949-03       132.0
3  1949-04       129.0
4  1949-05       121.0

## 4. Exploring Unique Values

### Question 17
Find the total number of **unique values** in the **Month** column.

In [19]:
df['Month'].nunique()

144

### Question 18
Find the total number of **unique values** in the **Passengers** column.

In [20]:
df['Passengers'].nunique

<bound method IndexOpsMixin.nunique of 0      112.0
1      118.0
2      132.0
3      129.0
4      121.0
       ...
139    606.0
140    508.0
141    461.0
142    390.0
143    432.0
Name: Passengers, Length: 144, dtype: float64>

### Question 19
Find which **Passengers** value appears most often using `value_counts()`.

In [28]:
df['Passengers'].value_counts()

Passengers
229.0    3
118.0    2
135.0    2
148.0    2
170.0    2
        ..
622.0    1
606.0    1
508.0    1
390.0    1
432.0    1
Name: count, Length: 118, dtype: int64

## 5. Basic Analysis and Filtering

### Question 20
Find the **maximum value** available in the **Passengers** column.

In [29]:
df['Passengers'].max()

np.float64(622.0)

### Question 21
Find the **minimum value** available in the **Passengers** column.

In [30]:
df['Passengers'].min()

np.float64(104.0)

### Question 22
Display all rows whose **Passengers** is greater than **400**.

In [31]:
df[df['Passengers']>400]

       Month  Passengers
90   1956-07       413.0
91   1956-08       405.0
101  1957-06       422.0
102  1957-07       465.0
103  1957-08       467.0
104  1957-09       404.0
113  1958-06       435.0
114  1958-07       491.0
115  1958-08       505.0
116  1958-09       404.0
122  1959-03       406.0
124  1959-05       420.0
125  1959-06       472.0
126  1959-07       548.0
127  1959-08       559.0
128  1959-09       463.0
129  1959-10       407.0
131  1959-12       405.0
132  1960-01       417.0
134  1960-03       419.0
135  1960-04       461.0
136  1960-05       472.0
137  1960-06       535.0
138  1960-07       622.0
139  1960-08       606.0
140  1960-09       508.0
141  1960-10       461.0
143  1960-12       432.0

### Question 23
Display all rows whose **Passengers** is less than **150**.

In [32]:
df[df['Passengers']<150]

      Month  Passengers
0   1949-01       112.0
1   1949-02       118.0
2   1949-03       132.0
3   1949-04       129.0
4   1949-05       121.0
5   1949-06       135.0
6   1949-07       148.0
7   1949-08       148.0
8   1949-09       136.0
9   1949-10       119.0
10  1949-11       104.0
11  1949-12       118.0
12  1950-01       115.0
13  1950-02       126.0
14  1950-03       141.0
15  1950-04       135.0
16  1950-05       125.0
17  1950-06       149.0
21  1950-10       133.0
22  1950-11       114.0
23  1950-12       140.0
24  1951-01       145.0
34  1951-11       146.0

### Question 24
Using `query()`, display all months having **Passengers greater than or equal to 300**.

In [34]:
df.query('Passengers >=300')

       Month  Passengers
66   1954-07       302.0
77   1955-06       315.0
78   1955-07       364.0
79   1955-08       347.0
80   1955-09       312.0
..       ...         ...
139  1960-08       606.0
140  1960-09       508.0
141  1960-10       461.0
142  1960-11       390.0
143  1960-12       432.0

[62 rows x 2 columns]

### Question 25
Display months having **Passengers greater than 200** and **less than 300**.

In [39]:
df.query('Passengers >200 & Passengers<300')

      Month  Passengers
41  1952-06       218.0
42  1952-07       230.0
43  1952-08       242.0
44  1952-09       209.0
50  1953-03       236.0
51  1953-04       235.0
52  1953-05       229.0
53  1953-06       243.0
54  1953-07       264.0
55  1953-08       272.0
56  1953-09       237.0
57  1953-10       211.0
59  1953-12       201.0
60  1954-01       204.0
62  1954-03       235.0
63  1954-04       227.0
64  1954-05       234.0
65  1954-06       264.0
67  1954-08       293.0
68  1954-09       259.0
69  1954-10       229.0
70  1954-11       203.0
71  1954-12       229.0
72  1955-01       242.0
73  1955-02       233.0
74  1955-03       267.0
75  1955-04       269.0
76  1955-05       270.0
81  1955-10       274.0
82  1955-11       237.0
83  1955-12       278.0
84  1956-01       284.0
85  1956-02       277.0
94  1956-11       271.0

## 6. Simple String Operations

### Question 26
Display all rows where **Month** starts with `1955` using a Pandas string method.

In [46]:
df[df['Month'].str.startswith('1955')]

      Month  Passengers
72  1955-01       242.0
73  1955-02       233.0
74  1955-03       267.0
75  1955-04       269.0
76  1955-05       270.0
77  1955-06       315.0
78  1955-07       364.0
79  1955-08       347.0
80  1955-09       312.0
81  1955-10       274.0
82  1955-11       237.0
83  1955-12       278.0

### Question 27
Extract the **year** (the first 4 characters) from the **Month** column using the `str` accessor and display the result.

In [47]:
df['Month'].str[:4]

0      1949
1      1949
2      1949
3      1949
4      1949
       ...
139    1960
140    1960
141    1960
142    1960
143    1960
Name: Month, Length: 144, dtype: str

## 7. Creating and Modifying Columns

### Question 28
Create a new column called **Traffic Level**. Store `High` when `Passengers` is greater than 300; otherwise store `Normal`. Use `apply()` with a `lambda` function.

In [49]:
df['Traffic Level'] = df['Passengers'].apply(lambda x:'High' if x>300 else 'Normal')
df

       Month  Passengers Traffic Level
0    1949-01       112.0        Normal
1    1949-02       118.0        Normal
2    1949-03       132.0        Normal
3    1949-04       129.0        Normal
4    1949-05       121.0        Normal
..       ...         ...           ...
139  1960-08       606.0          High
140  1960-09       508.0          High
141  1960-10       461.0          High
142  1960-11       390.0          High
143  1960-12       432.0          High

[144 rows x 3 columns]

### Question 29
Display the first **10 rows** after creating the **Traffic Level** column.

In [50]:
df.head(10)

     Month  Passengers Traffic Level
0  1949-01       112.0        Normal
1  1949-02       118.0        Normal
2  1949-03       132.0        Normal
3  1949-04       129.0        Normal
4  1949-05       121.0        Normal
5  1949-06       135.0        Normal
6  1949-07       148.0        Normal
7  1949-08       148.0        Normal
8  1949-09       136.0        Normal
9  1949-10       119.0        Normal

### Question 30
Remove the **Traffic Level** column using `drop()`.

In [53]:
df = df.drop('Traffic Level',axis=1)
df

       Month  Passengers
0    1949-01       112.0
1    1949-02       118.0
2    1949-03       132.0
3    1949-04       129.0
4    1949-05       121.0
..       ...         ...
139  1960-08       606.0
140  1960-09       508.0
141  1960-10       461.0
142  1960-11       390.0
143  1960-12       432.0

[144 rows x 2 columns]

### Question 31
Create a new column called **Year** by taking the first 4 characters of **Month** and converting them to integers using `astype(int)`.

In [55]:
df['Year'] = df['Month'].str[:4].astype(int)
df

       Month  Passengers  Year
0    1949-01       112.0  1949
1    1949-02       118.0  1949
2    1949-03       132.0  1949
3    1949-04       129.0  1949
4    1949-05       121.0  1949
..       ...         ...   ...
139  1960-08       606.0  1960
140  1960-09       508.0  1960
141  1960-10       461.0  1960
142  1960-11       390.0  1960
143  1960-12       432.0  1960

[144 rows x 3 columns]

## 8. Conversion and Export

### Question 32
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [56]:
df.select_dtypes(include='number')

     Passengers  Year
0         112.0  1949
1         118.0  1949
2         132.0  1949
3         129.0  1949
4         121.0  1949
..          ...   ...
139       606.0  1960
140       508.0  1960
141       461.0  1960
142       390.0  1960
143       432.0  1960

[144 rows x 2 columns]

### Question 33
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [57]:
df.head(10).to_numpy()

array([['1949-01', 112.0, 1949],
       ['1949-02', 118.0, 1949],
       ['1949-03', 132.0, 1949],
       ['1949-04', 129.0, 1949],
       ['1949-05', 121.0, 1949],
       ['1949-06', 135.0, 1949],
       ['1949-07', 148.0, 1949],
       ['1949-08', 148.0, 1949],
       ['1949-09', 136.0, 1949],
       ['1949-10', 119.0, 1949]], dtype=object)

### Question 34
Convert all column names to lowercase using `columns.str.lower()`.

In [59]:
df.columns = df.columns.str.lower()
df

       month  passengers  year
0    1949-01       112.0  1949
1    1949-02       118.0  1949
2    1949-03       132.0  1949
3    1949-04       129.0  1949
4    1949-05       121.0  1949
..       ...         ...   ...
139  1960-08       606.0  1960
140  1960-09       508.0  1960
141  1960-10       461.0  1960
142  1960-11       390.0  1960
143  1960-12       432.0  1960

[144 rows x 3 columns]

### Question 35
Save the DataFrame as a new CSV file named **Airline_Passengers_Practice_Output.csv** using `to_csv()` without saving the index.

In [60]:
df.to_csv('Airline_Passengers_Practice_Output.csv',index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.